/*
 MB91F465X Series I/O register declaration file V01L03
 ALL RIGHTS RESERVED, COPYRIGHT (C) FUJITSU MICROELECTRONICS LIMITED 2008
 LICENSED MATERIAL - PROGRAM PROPERTY OF FUJITSU MICROELECTRONICS LIMITED
*/


#ifdef __IO_DEFINE
	.SECTION	IO_PDR14,IO,LOCATE=0xE
_IO_PDR14:
__pdr14:	.res.b	1
PDR14	.equ	0xE
#endif
	.GLOBAL	_IO_PDR14, __pdr14, PDR14

#ifdef __IO_DEFINE
	.SECTION	IO_PDR15,IO,LOCATE=0xF
_IO_PDR15:
__pdr15:	.res.b	1
PDR15	.equ	0xF
#endif
	.GLOBAL	_IO_PDR15, __pdr15, PDR15

#ifdef __IO_DEFINE
	.SECTION	IO_PDR16,IO,LOCATE=0x10
_IO_PDR16:
__pdr16:	.res.b	1
PDR16	.equ	0x10
#endif
	.GLOBAL	_IO_PDR16, __pdr16, PDR16

#ifdef __IO_DEFINE
	.SECTION	IO_PDR17,IO,LOCATE=0x11
_IO_PDR17:
__pdr17:	.res.b	1
PDR17	.equ	0x11
#endif
	.GLOBAL	_IO_PDR17, __pdr17, PDR17

#ifdef __IO_DEFINE
	.SECTION	IO_PDR18,IO,LOCATE=0x12
_IO_PDR18:
__pdr18:	.res.b	1
PDR18	.equ	0x12
#endif
	.GLOBAL	_IO_PDR18, __pdr18, PDR18

#ifdef __IO_DEFINE
	.SECTION	IO_PDR19,IO,LOCATE=0x13
_IO_PDR19:
__pdr19:	.res.b	1
PDR19	.equ	0x13
#endif
	.GLOBAL	_IO_PDR19, __pdr19, PDR19

#ifdef __IO_DEFINE
	.SECTION	IO_PDR22,IO,LOCATE=0x16
_IO_PDR22:
__pdr22:	.res.b	1
PDR22	.equ	0x16
#endif
	.GLOBAL	_IO_PDR22, __pdr22, PDR22

#ifdef __IO_DEFINE
	.SECTION	IO_PDR23,IO,LOCATE=0x17
_IO_PDR23:
__pdr23:	.res.b	1
PDR23	.equ	0x17
#endif
	.GLOBAL	_IO_PDR23, __pdr23, PDR23

#ifdef __IO_DEFINE
	.SECTION	IO_PDR24,IO,LOCATE=0x18
_IO_PDR24:
__pdr24:	.res.b	1
PDR24	.equ	0x18
#endif
	.GLOBAL	_IO_PDR24, __pdr24, PDR24

#ifdef __IO_DEFINE
	.SECTION	IO_PDR27,IO,LOCATE=0x1B
_IO_PDR27:
__pdr27:	.res.b	1
PDR27	.equ	0x1B
#endif
	.GLOBAL	_IO_PDR27, __pdr27, PDR27

#ifdef __IO_DEFINE
	.SECTION	IO_PDR28,IO,LOCATE=0x1C
_IO_PDR28:
__pdr28:	.res.b	1
PDR28	.equ	0x1C
#endif
	.GLOBAL	_IO_PDR28, __pdr28, PDR28

#ifdef __IO_DEFINE
	.SECTION	IO_PDR29,IO,LOCATE=0x1D
_IO_PDR29:
__pdr29:	.res.b	1
PDR29	.equ	0x1D
#endif
	.GLOBAL	_IO_PDR29, __pdr29, PDR29

#ifdef __IO_DEFINE
	.SECTION	IO_PDR31,IO,LOCATE=0x1F
_IO_PDR31:
__pdr31:	.res.b	1
PDR31	.equ	0x1F
#endif
	.GLOBAL	_IO_PDR31, __pdr31, PDR31

#ifdef __IO_DEFINE
	.SECTION	IO_EIRR0,IO,LOCATE=0x30
_IO_EIRR0:
__eirr0:	.res.b	1
EIRR0	.equ	0x30
#endif
	.GLOBAL	_IO_EIRR0, __eirr0, EIRR0

#ifdef __IO_DEFINE
	.SECTION	IO_ENIR0,IO,LOCATE=0x31
_IO_ENIR0:
__enir0:	.res.b	1
ENIR0	.equ	0x31
#endif
	.GLOBAL	_IO_ENIR0, __enir0, ENIR0

#ifdef __IO_DEFINE
	.SECTION	IO_ELVR0,IO,LOCATE=0x32
_IO_ELVR0:
__elvr0:	.res.b	2
ELVR0	.equ	0x32
#endif
	.GLOBAL	_IO_ELVR0, __elvr0, ELVR0

#ifdef __IO_DEFINE
	.SECTION	IO_EIRR1,IO,LOCATE=0x34
_IO_EIRR1:
__eirr1:	.res.b	1
EIRR1	.equ	0x34
#endif
	.GLOBAL	_IO_EIRR1, __eirr1, EIRR1

#ifdef __IO_DEFINE
	.SECTION	IO_ENIR1,IO,LOCATE=0x35
_IO_ENIR1:
__enir1:	.res.b	1
ENIR1	.equ	0x35
#endif
	.GLOBAL	_IO_ENIR1, __enir1, ENIR1

#ifdef __IO_DEFINE
	.SECTION	IO_ELVR1,IO,LOCATE=0x36
_IO_ELVR1:
__elvr1:	.res.b	2
ELVR1	.equ	0x36
#endif
	.GLOBAL	_IO_ELVR1, __elvr1, ELVR1

#ifdef __IO_DEFINE
	.SECTION	IO_DICR,IO,LOCATE=0x38
_IO_DICR:
__dicr:	.res.b	1
DICR	.equ	0x38
#endif
	.GLOBAL	_IO_DICR, __dicr, DICR

#ifdef __IO_DEFINE
	.SECTION	IO_HRCL,IO,LOCATE=0x39
_IO_HRCL:
__hrcl:	.res.b	1
HRCL	.equ	0x39
#endif
	.GLOBAL	_IO_HRCL, __hrcl, HRCL

#ifdef __IO_DEFINE
	.SECTION	IO_RBSYNC,IO,LOCATE=0x40
_IO_RBSYNC:
__RBSYNC:	.res.b	2
RBSYNC	.equ	0x40
#endif
	.GLOBAL	_IO_RBSYNC, __RBSYNC, RBSYNC

#ifdef __IO_DEFINE
	.SECTION	IO_SCR04,IO,LOCATE=0x60
_IO_SCR04:
__scr04:	.res.b	1
SCR04	.equ	0x60
#endif
	.GLOBAL	_IO_SCR04, __scr04, SCR04

#ifdef __IO_DEFINE
	.SECTION	IO_SMR04,IO,LOCATE=0x61
_IO_SMR04:
__smr04:	.res.b	1
SMR04	.equ	0x61
#endif
	.GLOBAL	_IO_SMR04, __smr04, SMR04

#ifdef __IO_DEFINE
	.SECTION	IO_SSR04,IO,LOCATE=0x62
_IO_SSR04:
__ssr04:	.res.b	1
SSR04	.equ	0x62
#endif
	.GLOBAL	_IO_SSR04, __ssr04, SSR04

#ifdef __IO_DEFINE
	.SECTION	IO_RDR04,IO,LOCATE=0x63
_IO_RDR04:
__RDR04:	.res.b	1
RDR04	.equ	0x63
#endif
	.GLOBAL	_IO_RDR04, __RDR04, RDR04

#ifdef __IO_DEFINE
	.SECTION	IO_ESCR04,IO,LOCATE=0x64
_IO_ESCR04:
__escr04:	.res.b	1
ESCR04	.equ	0x64
#endif
	.GLOBAL	_IO_ESCR04, __escr04, ESCR04

#ifdef __IO_DEFINE
	.SECTION	IO_ECCR04,IO,LOCATE=0x65
_IO_ECCR04:
__eccr04:	.res.b	1
ECCR04	.equ	0x65
#endif
	.GLOBAL	_IO_ECCR04, __eccr04, ECCR04

#ifdef __IO_DEFINE
	.SECTION	IO_FSR04,IO,LOCATE=0x66
_IO_FSR04:
__FSR04:	.res.b	1
FSR04	.equ	0x66
#endif
	.GLOBAL	_IO_FSR04, __FSR04, FSR04

#ifdef __IO_DEFINE
	.SECTION	IO_FCR04,IO,LOCATE=0x67
_IO_FCR04:
__fcr04:	.res.b	1
FCR04	.equ	0x67
#endif
	.GLOBAL	_IO_FCR04, __fcr04, FCR04

#ifdef __IO_DEFINE
	.SECTION	IO_SCR06,IO,LOCATE=0x70
_IO_SCR06:
__scr06:	.res.b	1
SCR06	.equ	0x70
#endif
	.GLOBAL	_IO_SCR06, __scr06, SCR06

#ifdef __IO_DEFINE
	.SECTION	IO_SMR06,IO,LOCATE=0x71
_IO_SMR06:
__smr06:	.res.b	1
SMR06	.equ	0x71
#endif
	.GLOBAL	_IO_SMR06, __smr06, SMR06

#ifdef __IO_DEFINE
	.SECTION	IO_SSR06,IO,LOCATE=0x72
_IO_SSR06:
__ssr06:	.res.b	1
SSR06	.equ	0x72
#endif
	.GLOBAL	_IO_SSR06, __ssr06, SSR06

#ifdef __IO_DEFINE
	.SECTION	IO_RDR06,IO,LOCATE=0x73
_IO_RDR06:
__RDR06:	.res.b	1
RDR06	.equ	0x73
#endif
	.GLOBAL	_IO_RDR06, __RDR06, RDR06

#ifdef __IO_DEFINE
	.SECTION	IO_ESCR06,IO,LOCATE=0x74
_IO_ESCR06:
__escr06:	.res.b	1
ESCR06	.equ	0x74
#endif
	.GLOBAL	_IO_ESCR06, __escr06, ESCR06

#ifdef __IO_DEFINE
	.SECTION	IO_ECCR06,IO,LOCATE=0x75
_IO_ECCR06:
__eccr06:	.res.b	1
ECCR06	.equ	0x75
#endif
	.GLOBAL	_IO_ECCR06, __eccr06, ECCR06

#ifdef __IO_DEFINE
	.SECTION	IO_FSR06,IO,LOCATE=0x76
_IO_FSR06:
__FSR06:	.res.b	1
FSR06	.equ	0x76
#endif
	.GLOBAL	_IO_FSR06, __FSR06, FSR06

#ifdef __IO_DEFINE
	.SECTION	IO_FCR06,IO,LOCATE=0x77
_IO_FCR06:
__fcr06:	.res.b	1
FCR06	.equ	0x77
#endif
	.GLOBAL	_IO_FCR06, __fcr06, FCR06

#ifdef __IO_DEFINE
	.SECTION	IO_SCR07,IO,LOCATE=0x78
_IO_SCR07:
__scr07:	.res.b	1
SCR07	.equ	0x78
#endif
	.GLOBAL	_IO_SCR07, __scr07, SCR07

#ifdef __IO_DEFINE
	.SECTION	IO_SMR07,IO,LOCATE=0x79
_IO_SMR07:
__smr07:	.res.b	1
SMR07	.equ	0x79
#endif
	.GLOBAL	_IO_SMR07, __smr07, SMR07

#ifdef __IO_DEFINE
	.SECTION	IO_SSR07,IO,LOCATE=0x7A
_IO_SSR07:
__ssr07:	.res.b	1
SSR07	.equ	0x7A
#endif
	.GLOBAL	_IO_SSR07, __ssr07, SSR07

#ifdef __IO_DEFINE
	.SECTION	IO_RDR07,IO,LOCATE=0x7B
_IO_RDR07:
__RDR07:	.res.b	1
RDR07	.equ	0x7B
#endif
	.GLOBAL	_IO_RDR07, __RDR07, RDR07

#ifdef __IO_DEFINE
	.SECTION	IO_ESCR07,IO,LOCATE=0x7C
_IO_ESCR07:
__escr07:	.res.b	1
ESCR07	.equ	0x7C
#endif
	.GLOBAL	_IO_ESCR07, __escr07, ESCR07

#ifdef __IO_DEFINE
	.SECTION	IO_ECCR07,IO,LOCATE=0x7D
_IO_ECCR07:
__eccr07:	.res.b	1
ECCR07	.equ	0x7D
#endif
	.GLOBAL	_IO_ECCR07, __eccr07, ECCR07

#ifdef __IO_DEFINE
	.SECTION	IO_FSR07,IO,LOCATE=0x7E
_IO_FSR07:
__FSR07:	.res.b	1
FSR07	.equ	0x7E
#endif
	.GLOBAL	_IO_FSR07, __FSR07, FSR07

#ifdef __IO_DEFINE
	.SECTION	IO_FCR07,IO,LOCATE=0x7F
_IO_FCR07:
__fcr07:	.res.b	1
FCR07	.equ	0x7F
#endif
	.GLOBAL	_IO_FCR07, __fcr07, FCR07

#ifdef __IO_DEFINE
	.SECTION	IO_BGR04,IO,LOCATE=0x88
_IO_BGR04:	
__bgr04:	.res.b	0
BGR04		.equ	0x88
_IO_BGR104:	.res.b	1
_IO_BGR004:	.res.b	1
#endif
	.GLOBAL	_IO_BGR04, __bgr04, BGR04
	.GLOBAL	_IO_BGR104
	.GLOBAL	_IO_BGR004

#ifdef __IO_DEFINE
	.SECTION	IO_BGR06,IO,LOCATE=0x8C
_IO_BGR06:	
__bgr06:	.res.b	0
BGR06		.equ	0x8C
_IO_BGR106:	.res.b	1
_IO_BGR006:	.res.b	1
#endif
	.GLOBAL	_IO_BGR06, __bgr06, BGR06
	.GLOBAL	_IO_BGR106
	.GLOBAL	_IO_BGR006

#ifdef __IO_DEFINE
	.SECTION	IO_BGR07,IO,LOCATE=0x8E
_IO_BGR07:	
__bgr07:	.res.b	0
BGR07		.equ	0x8E
_IO_BGR107:	.res.b	1
_IO_BGR007:	.res.b	1
#endif
	.GLOBAL	_IO_BGR07, __bgr07, BGR07
	.GLOBAL	_IO_BGR107
	.GLOBAL	_IO_BGR007

#ifdef __IO_DEFINE
	.SECTION	IO_IIC0,IO,LOCATE=0xD0
_IO_IIC0:	.res.b	0
_IO_IIC0_IO_IBCR0:	.res.b	1
_IO_IIC0_IO_IBSR0:	.res.b	1
_IO_IIC0_IO_ITBA0:	.res.b	2
_IO_IIC0_IO_ITMK0:	.res.b	2
_IO_IIC0_IO_ISMK0:	.res.b	1
_IO_IIC0_IO_ISBA0:	.res.b	1
_IO_IIC0_IO_RESV1:	.res.b	1
_IO_IIC0_IO_IDAR0:	.res.b	1
_IO_IIC0_IO_ICCR0:	.res.b	1
_IO_IIC0_IO_RESV2:	.res.b	1
#endif
	.GLOBAL	_IO_IIC0
	.GLOBAL	_IO_IIC0_IO_IBCR0
	.GLOBAL	_IO_IIC0_IO_IBSR0
	.GLOBAL	_IO_IIC0_IO_ITBA0
	.GLOBAL	_IO_IIC0_IO_ITMK0
	.GLOBAL	_IO_IIC0_IO_ISMK0
	.GLOBAL	_IO_IIC0_IO_ISBA0
	.GLOBAL	_IO_IIC0_IO_RESV1
	.GLOBAL	_IO_IIC0_IO_IDAR0
	.GLOBAL	_IO_IIC0_IO_ICCR0
	.GLOBAL	_IO_IIC0_IO_RESV2

#ifdef __IO_DEFINE
	.SECTION	IO_GCN10,DATA,locate=0x100
_IO_GCN10:
__gcn10:	.res.b	2
GCN10	.equ	0x100
#endif
	.GLOBAL	_IO_GCN10, __gcn10, GCN10

#ifdef __IO_DEFINE
	.SECTION	IO_GCN20,DATA,locate=0x103
_IO_GCN20:
__gcn20:	.res.b	1
GCN20	.equ	0x103
#endif
	.GLOBAL	_IO_GCN20, __gcn20, GCN20

#ifdef __IO_DEFINE
	.SECTION	IO_GCN11,DATA,locate=0x104
_IO_GCN11:
__gcn11:	.res.b	2
GCN11	.equ	0x104
#endif
	.GLOBAL	_IO_GCN11, __gcn11, GCN11

#ifdef __IO_DEFINE
	.SECTION	IO_GCN21,DATA,locate=0x107
_IO_GCN21:
__gcn21:	.res.b	1
GCN21	.equ	0x107
#endif
	.GLOBAL	_IO_GCN21, __gcn21, GCN21

#ifdef __IO_DEFINE
	.SECTION	IO_GCN12,DATA,locate=0x108
_IO_GCN12:
__gcn12:	.res.b	2
GCN12	.equ	0x108
#endif
	.GLOBAL	_IO_GCN12, __gcn12, GCN12

#ifdef __IO_DEFINE
	.SECTION	IO_GCN22,DATA,locate=0x10B
_IO_GCN22:
__gcn22:	.res.b	1
GCN22	.equ	0x10B
#endif
	.GLOBAL	_IO_GCN22, __gcn22, GCN22

#ifdef __IO_DEFINE
	.SECTION	IO_PTMR00,DATA,locate=0x110
_IO_PTMR00:
__PTMR00:	.res.b	2
PTMR00	.equ	0x110
#endif
	.GLOBAL	_IO_PTMR00, __PTMR00, PTMR00

#ifdef __IO_DEFINE
	.SECTION	IO_PCSR00,DATA,locate=0x112
_IO_PCSR00:
__PCSR00:	.res.b	2
PCSR00	.equ	0x112
#endif
	.GLOBAL	_IO_PCSR00, __PCSR00, PCSR00

#ifdef __IO_DEFINE
	.SECTION	IO_PDUT00,DATA,locate=0x114
_IO_PDUT00:
__PDUT00:	.res.b	2
PDUT00	.equ	0x114
#endif
	.GLOBAL	_IO_PDUT00, __PDUT00, PDUT00

#ifdef __IO_DEFINE
	.SECTION	IO_PCN00,DATA,locate=0x116
_IO_PCN00:
__pcn00:	.res.b	2
PCN00	.equ	0x116
#endif
	.GLOBAL	_IO_PCN00, __pcn00, PCN00

#ifdef __IO_DEFINE
	.SECTION	IO_PTMR01,DATA,locate=0x118
_IO_PTMR01:
__PTMR01:	.res.b	2
PTMR01	.equ	0x118
#endif
	.GLOBAL	_IO_PTMR01, __PTMR01, PTMR01

#ifdef __IO_DEFINE
	.SECTION	IO_PCSR01,DATA,locate=0x11A
_IO_PCSR01:
__PCSR01:	.res.b	2
PCSR01	.equ	0x11A
#endif
	.GLOBAL	_IO_PCSR01, __PCSR01, PCSR01

#ifdef __IO_DEFINE
	.SECTION	IO_PDUT01,DATA,locate=0x11C
_IO_PDUT01:
__PDUT01:	.res.b	2
PDUT01	.equ	0x11C
#endif
	.GLOBAL	_IO_PDUT01, __PDUT01, PDUT01

#ifdef __IO_DEFINE
	.SECTION	IO_PCN01,DATA,locate=0x11E
_IO_PCN01:
__pcn01:	.res.b	2
PCN01	.equ	0x11E
#endif
	.GLOBAL	_IO_PCN01, __pcn01, PCN01

#ifdef __IO_DEFINE
	.SECTION	IO_PTMR02,DATA,locate=0x120
_IO_PTMR02:
__PTMR02:	.res.b	2
PTMR02	.equ	0x120
#endif
	.GLOBAL	_IO_PTMR02, __PTMR02, PTMR02

#ifdef __IO_DEFINE
	.SECTION	IO_PCSR02,DATA,locate=0x122
_IO_PCSR02:
__PCSR02:	.res.b	2
PCSR02	.equ	0x122
#endif
	.GLOBAL	_IO_PCSR02, __PCSR02, PCSR02

#ifdef __IO_DEFINE
	.SECTION	IO_PDUT02,DATA,locate=0x124
_IO_PDUT02:
__PDUT02:	.res.b	2
PDUT02	.equ	0x124
#endif
	.GLOBAL	_IO_PDUT02, __PDUT02, PDUT02

#ifdef __IO_DEFINE
	.SECTION	IO_PCN02,DATA,locate=0x126
_IO_PCN02:
__pcn02:	.res.b	2
PCN02	.equ	0x126
#endif
	.GLOBAL	_IO_PCN02, __pcn02, PCN02

#ifdef __IO_DEFINE
	.SECTION	IO_PTMR03,DATA,locate=0x128
_IO_PTMR03:
__PTMR03:	.res.b	2
PTMR03	.equ	0x128
#endif
	.GLOBAL	_IO_PTMR03, __PTMR03, PTMR03

#ifdef __IO_DEFINE
	.SECTION	IO_PCSR03,DATA,locate=0x12A
_IO_PCSR03:
__PCSR03:	.res.b	2
PCSR03	.equ	0x12A
#endif
	.GLOBAL	_IO_PCSR03, __PCSR03, PCSR03

#ifdef __IO_DEFINE
	.SECTION	IO_PDUT03,DATA,locate=0x12C
_IO_PDUT03:
__PDUT03:	.res.b	2
PDUT03	.equ	0x12C
#endif
	.GLOBAL	_IO_PDUT03, __PDUT03, PDUT03

#ifdef __IO_DEFINE
	.SECTION	IO_PCN03,DATA,locate=0x12E
_IO_PCN03:
__pcn03:	.res.b	2
PCN03	.equ	0x12E
#endif
	.GLOBAL	_IO_PCN03, __pcn03, PCN03

#ifdef __IO_DEFINE
	.SECTION	IO_PTMR04,DATA,locate=0x130
_IO_PTMR04:
__PTMR04:	.res.b	2
PTMR04	.equ	0x130
#endif
	.GLOBAL	_IO_PTMR04, __PTMR04, PTMR04

#ifdef __IO_DEFINE
	.SECTION	IO_PCSR04,DATA,locate=0x132
_IO_PCSR04:
__PCSR04:	.res.b	2
PCSR04	.equ	0x132
#endif
	.GLOBAL	_IO_PCSR04, __PCSR04, PCSR04

#ifdef __IO_DEFINE
	.SECTION	IO_PDUT04,DATA,locate=0x134
_IO_PDUT04:
__PDUT04:	.res.b	2
PDUT04	.equ	0x134
#endif
	.GLOBAL	_IO_PDUT04, __PDUT04, PDUT04

#ifdef __IO_DEFINE
	.SECTION	IO_PCN04,DATA,locate=0x136
_IO_PCN04:
__pcn04:	.res.b	2
PCN04	.equ	0x136
#endif
	.GLOBAL	_IO_PCN04, __pcn04, PCN04

#ifdef __IO_DEFINE
	.SECTION	IO_PTMR05,DATA,locate=0x138
_IO_PTMR05:
__PTMR05:	.res.b	2
PTMR05	.equ	0x138
#endif
	.GLOBAL	_IO_PTMR05, __PTMR05, PTMR05

#ifdef __IO_DEFINE
	.SECTION	IO_PCSR05,DATA,locate=0x13A
_IO_PCSR05:
__PCSR05:	.res.b	2
PCSR05	.equ	0x13A
#endif
	.GLOBAL	_IO_PCSR05, __PCSR05, PCSR05

#ifdef __IO_DEFINE
	.SECTION	IO_PDUT05,DATA,locate=0x13C
_IO_PDUT05:
__PDUT05:	.res.b	2
PDUT05	.equ	0x13C
#endif
	.GLOBAL	_IO_PDUT05, __PDUT05, PDUT05

#ifdef __IO_DEFINE
	.SECTION	IO_PCN05,DATA,locate=0x13E
_IO_PCN05:
__pcn05:	.res.b	2
PCN05	.equ	0x13E
#endif
	.GLOBAL	_IO_PCN05, __pcn05, PCN05

#ifdef __IO_DEFINE
	.SECTION	IO_PTMR06,DATA,locate=0x140
_IO_PTMR06:
__PTMR06:	.res.b	2
PTMR06	.equ	0x140
#endif
	.GLOBAL	_IO_PTMR06, __PTMR06, PTMR06

#ifdef __IO_DEFINE
	.SECTION	IO_PCSR06,DATA,locate=0x142
_IO_PCSR06:
__PCSR06:	.res.b	2
PCSR06	.equ	0x142
#endif
	.GLOBAL	_IO_PCSR06, __PCSR06, PCSR06

#ifdef __IO_DEFINE
	.SECTION	IO_PDUT06,DATA,locate=0x144
_IO_PDUT06:
__PDUT06:	.res.b	2
PDUT06	.equ	0x144
#endif
	.GLOBAL	_IO_PDUT06, __PDUT06, PDUT06

#ifdef __IO_DEFINE
	.SECTION	IO_PCN06,DATA,locate=0x146
_IO_PCN06:
__pcn06:	.res.b	2
PCN06	.equ	0x146
#endif
	.GLOBAL	_IO_PCN06, __pcn06, PCN06

#ifdef __IO_DEFINE
	.SECTION	IO_PTMR07,DATA,locate=0x148
_IO_PTMR07:
__PTMR07:	.res.b	2
PTMR07	.equ	0x148
#endif
	.GLOBAL	_IO_PTMR07, __PTMR07, PTMR07

#ifdef __IO_DEFINE
	.SECTION	IO_PCSR07,DATA,locate=0x14A
_IO_PCSR07:
__PCSR07:	.res.b	2
PCSR07	.equ	0x14A
#endif
	.GLOBAL	_IO_PCSR07, __PCSR07, PCSR07

#ifdef __IO_DEFINE
	.SECTION	IO_PDUT07,DATA,locate=0x14C
_IO_PDUT07:
__PDUT07:	.res.b	2
PDUT07	.equ	0x14C
#endif
	.GLOBAL	_IO_PDUT07, __PDUT07, PDUT07

#ifdef __IO_DEFINE
	.SECTION	IO_PCN07,DATA,locate=0x14E
_IO_PCN07:
__pcn07:	.res.b	2
PCN07	.equ	0x14E
#endif
	.GLOBAL	_IO_PCN07, __pcn07, PCN07

#ifdef __IO_DEFINE
	.SECTION	IO_PTMR08,DATA,locate=0x150
_IO_PTMR08:
__PTMR08:	.res.b	2
PTMR08	.equ	0x150
#endif
	.GLOBAL	_IO_PTMR08, __PTMR08, PTMR08

#ifdef __IO_DEFINE
	.SECTION	IO_PCSR08,DATA,locate=0x152
_IO_PCSR08:
__PCSR08:	.res.b	2
PCSR08	.equ	0x152
#endif
	.GLOBAL	_IO_PCSR08, __PCSR08, PCSR08

#ifdef __IO_DEFINE
	.SECTION	IO_PDUT08,DATA,locate=0x154
_IO_PDUT08:
__PDUT08:	.res.b	2
PDUT08	.equ	0x154
#endif
	.GLOBAL	_IO_PDUT08, __PDUT08, PDUT08

#ifdef __IO_DEFINE
	.SECTION	IO_PCN08,DATA,locate=0x156
_IO_PCN08:
__pcn08:	.res.b	2
PCN08	.equ	0x156
#endif
	.GLOBAL	_IO_PCN08, __pcn08, PCN08

#ifdef __IO_DEFINE
	.SECTION	IO_PTMR09,DATA,locate=0x158
_IO_PTMR09:
__PTMR09:	.res.b	2
PTMR09	.equ	0x158
#endif
	.GLOBAL	_IO_PTMR09, __PTMR09, PTMR09

#ifdef __IO_DEFINE
	.SECTION	IO_PCSR09,DATA,locate=0x15A
_IO_PCSR09:
__PCSR09:	.res.b	2
PCSR09	.equ	0x15A
#endif
	.GLOBAL	_IO_PCSR09, __PCSR09, PCSR09

#ifdef __IO_DEFINE
	.SECTION	IO_PDUT09,DATA,locate=0x15C
_IO_PDUT09:
__PDUT09:	.res.b	2
PDUT09	.equ	0x15C
#endif
	.GLOBAL	_IO_PDUT09, __PDUT09, PDUT09

#ifdef __IO_DEFINE
	.SECTION	IO_PCN09,DATA,locate=0x15E
_IO_PCN09:
__pcn09:	.res.b	2
PCN09	.equ	0x15E
#endif
	.GLOBAL	_IO_PCN09, __pcn09, PCN09

#ifdef __IO_DEFINE
	.SECTION	IO_PTMR10,DATA,locate=0x160
_IO_PTMR10:
__PTMR10:	.res.b	2
PTMR10	.equ	0x160
#endif
	.GLOBAL	_IO_PTMR10, __PTMR10, PTMR10

#ifdef __IO_DEFINE
	.SECTION	IO_PCSR10,DATA,locate=0x162
_IO_PCSR10:
__PCSR10:	.res.b	2
PCSR10	.equ	0x162
#endif
	.GLOBAL	_IO_PCSR10, __PCSR10, PCSR10

#ifdef __IO_DEFINE
	.SECTION	IO_PDUT10,DATA,locate=0x164
_IO_PDUT10:
__PDUT10:	.res.b	2
PDUT10	.equ	0x164
#endif
	.GLOBAL	_IO_PDUT10, __PDUT10, PDUT10

#ifdef __IO_DEFINE
	.SECTION	IO_PCN10,DATA,locate=0x166
_IO_PCN10:
__pcn10:	.res.b	2
PCN10	.equ	0x166
#endif
	.GLOBAL	_IO_PCN10, __pcn10, PCN10

#ifdef __IO_DEFINE
	.SECTION	IO_PTMR11,DATA,locate=0x168
_IO_PTMR11:
__PTMR11:	.res.b	2
PTMR11	.equ	0x168
#endif
	.GLOBAL	_IO_PTMR11, __PTMR11, PTMR11

#ifdef __IO_DEFINE
	.SECTION	IO_PCSR11,DATA,locate=0x16A
_IO_PCSR11:
__PCSR11:	.res.b	2
PCSR11	.equ	0x16A
#endif
	.GLOBAL	_IO_PCSR11, __PCSR11, PCSR11

#ifdef __IO_DEFINE
	.SECTION	IO_PDUT11,DATA,locate=0x16C
_IO_PDUT11:
__PDUT11:	.res.b	2
PDUT11	.equ	0x16C
#endif
	.GLOBAL	_IO_PDUT11, __PDUT11, PDUT11

#ifdef __IO_DEFINE
	.SECTION	IO_PCN11,DATA,locate=0x16E
_IO_PCN11:
__pcn11:	.res.b	2
PCN11	.equ	0x16E
#endif
	.GLOBAL	_IO_PCN11, __pcn11, PCN11

#ifdef __IO_DEFINE
	.SECTION	IO_ICS01,DATA,locate=0x181
_IO_ICS01:
__ics01:	.res.b	1
ICS01	.equ	0x181
#endif
	.GLOBAL	_IO_ICS01, __ics01, ICS01

#ifdef __IO_DEFINE
	.SECTION	IO_ICS23,DATA,locate=0x183
_IO_ICS23:
__ics23:	.res.b	1
ICS23	.equ	0x183
#endif
	.GLOBAL	_IO_ICS23, __ics23, ICS23

#ifdef __IO_DEFINE
	.SECTION	IO_IPCP0,DATA,locate=0x184
_IO_IPCP0:
__IPCP0:	.res.b	2
IPCP0	.equ	0x184
#endif
	.GLOBAL	_IO_IPCP0, __IPCP0, IPCP0

#ifdef __IO_DEFINE
	.SECTION	IO_IPCP1,DATA,locate=0x186
_IO_IPCP1:
__IPCP1:	.res.b	2
IPCP1	.equ	0x186
#endif
	.GLOBAL	_IO_IPCP1, __IPCP1, IPCP1

#ifdef __IO_DEFINE
	.SECTION	IO_IPCP2,DATA,locate=0x188
_IO_IPCP2:
__IPCP2:	.res.b	2
IPCP2	.equ	0x188
#endif
	.GLOBAL	_IO_IPCP2, __IPCP2, IPCP2

#ifdef __IO_DEFINE
	.SECTION	IO_IPCP3,DATA,locate=0x18A
_IO_IPCP3:
__IPCP3:	.res.b	2
IPCP3	.equ	0x18A
#endif
	.GLOBAL	_IO_IPCP3, __IPCP3, IPCP3

#ifdef __IO_DEFINE
	.SECTION	IO_OCS01,DATA,locate=0x18C
_IO_OCS01:
__ocs01:	.res.b	2
OCS01	.equ	0x18C
#endif
	.GLOBAL	_IO_OCS01, __ocs01, OCS01

#ifdef __IO_DEFINE
	.SECTION	IO_OCS23,DATA,locate=0x18E
_IO_OCS23:
__ocs23:	.res.b	2
OCS23	.equ	0x18E
#endif
	.GLOBAL	_IO_OCS23, __ocs23, OCS23

#ifdef __IO_DEFINE
	.SECTION	IO_OCCP0,DATA,locate=0x190
_IO_OCCP0:
__OCCP0:	.res.b	2
OCCP0	.equ	0x190
#endif
	.GLOBAL	_IO_OCCP0, __OCCP0, OCCP0

#ifdef __IO_DEFINE
	.SECTION	IO_OCCP1,DATA,locate=0x192
_IO_OCCP1:
__OCCP1:	.res.b	2
OCCP1	.equ	0x192
#endif
	.GLOBAL	_IO_OCCP1, __OCCP1, OCCP1

#ifdef __IO_DEFINE
	.SECTION	IO_OCCP2,DATA,locate=0x194
_IO_OCCP2:
__OCCP2:	.res.b	2
OCCP2	.equ	0x194
#endif
	.GLOBAL	_IO_OCCP2, __OCCP2, OCCP2

#ifdef __IO_DEFINE
	.SECTION	IO_OCCP3,DATA,locate=0x196
_IO_OCCP3:
__OCCP3:	.res.b	2
OCCP3	.equ	0x196
#endif
	.GLOBAL	_IO_OCCP3, __OCCP3, OCCP3

#ifdef __IO_DEFINE
	.SECTION	IO_AD,DATA,locate=0x1A0
_IO_AD:	.res.b	0
_IO_AD_IO_ADER:	.res.b	4
_IO_AD_IO_ADCS1:	.res.b	1
_IO_AD_IO_ADCS0:	.res.b	1
_IO_AD_IO_ADCR01:	.res.b	2
_IO_AD_IO_ADCT01:	.res.b	2
_IO_AD_IO_ADSCH:	.res.b	1
_IO_AD_IO_ADECH:	.res.b	1
#endif
	.GLOBAL	_IO_AD
	.GLOBAL	_IO_AD_IO_ADER
	.GLOBAL	_IO_AD_IO_ADCS1
	.GLOBAL	_IO_AD_IO_ADCS0
	.GLOBAL	_IO_AD_IO_ADCR01
	.GLOBAL	_IO_AD_IO_ADCT01
	.GLOBAL	_IO_AD_IO_ADSCH
	.GLOBAL	_IO_AD_IO_ADECH

#ifdef __IO_DEFINE
	.SECTION	IO_TMRLR0,DATA,locate=0x1B0
_IO_TMRLR0:
__TMRLR0:	.res.b	2
TMRLR0	.equ	0x1B0
#endif
	.GLOBAL	_IO_TMRLR0, __TMRLR0, TMRLR0

#ifdef __IO_DEFINE
	.SECTION	IO_TMR0,DATA,locate=0x1B2
_IO_TMR0:
__TMR0:	.res.b	2
TMR0	.equ	0x1B2
#endif
	.GLOBAL	_IO_TMR0, __TMR0, TMR0

#ifdef __IO_DEFINE
	.SECTION	IO_TMCSR0,DATA,locate=0x1B6
_IO_TMCSR0:
__tmcsr0:	.res.b	2
TMCSR0	.equ	0x1B6
#endif
	.GLOBAL	_IO_TMCSR0, __tmcsr0, TMCSR0

#ifdef __IO_DEFINE
	.SECTION	IO_TMRLR1,DATA,locate=0x1B8
_IO_TMRLR1:
__TMRLR1:	.res.b	2
TMRLR1	.equ	0x1B8
#endif
	.GLOBAL	_IO_TMRLR1, __TMRLR1, TMRLR1

#ifdef __IO_DEFINE
	.SECTION	IO_TMR1,DATA,locate=0x1BA
_IO_TMR1:
__TMR1:	.res.b	2
TMR1	.equ	0x1BA
#endif
	.GLOBAL	_IO_TMR1, __TMR1, TMR1

#ifdef __IO_DEFINE
	.SECTION	IO_TMCSR1,DATA,locate=0x1BE
_IO_TMCSR1:
__tmcsr1:	.res.b	2
TMCSR1	.equ	0x1BE
#endif
	.GLOBAL	_IO_TMCSR1, __tmcsr1, TMCSR1

#ifdef __IO_DEFINE
	.SECTION	IO_TMRLR2,DATA,locate=0x1C0
_IO_TMRLR2:
__TMRLR2:	.res.b	2
TMRLR2	.equ	0x1C0
#endif
	.GLOBAL	_IO_TMRLR2, __TMRLR2, TMRLR2

#ifdef __IO_DEFINE
	.SECTION	IO_TMR2,DATA,locate=0x1C2
_IO_TMR2:
__TMR2:	.res.b	2
TMR2	.equ	0x1C2
#endif
	.GLOBAL	_IO_TMR2, __TMR2, TMR2

#ifdef __IO_DEFINE
	.SECTION	IO_TMCSR2,DATA,locate=0x1C6
_IO_TMCSR2:
__tmcsr2:	.res.b	2
TMCSR2	.equ	0x1C6
#endif
	.GLOBAL	_IO_TMCSR2, __tmcsr2, TMCSR2

#ifdef __IO_DEFINE
	.SECTION	IO_TMRLR3,DATA,locate=0x1C8
_IO_TMRLR3:
__TMRLR3:	.res.b	2
TMRLR3	.equ	0x1C8
#endif
	.GLOBAL	_IO_TMRLR3, __TMRLR3, TMRLR3

#ifdef __IO_DEFINE
	.SECTION	IO_TMR3,DATA,locate=0x1CA
_IO_TMR3:
__TMR3:	.res.b	2
TMR3	.equ	0x1CA
#endif
	.GLOBAL	_IO_TMR3, __TMR3, TMR3

#ifdef __IO_DEFINE
	.SECTION	IO_TMCSR3,DATA,locate=0x1CE
_IO_TMCSR3:
__tmcsr3:	.res.b	2
TMCSR3	.equ	0x1CE
#endif
	.GLOBAL	_IO_TMCSR3, __tmcsr3, TMCSR3

#ifdef __IO_DEFINE
	.SECTION	IO_TMRLR4,DATA,locate=0x1D0
_IO_TMRLR4:
__TMRLR4:	.res.b	2
TMRLR4	.equ	0x1D0
#endif
	.GLOBAL	_IO_TMRLR4, __TMRLR4, TMRLR4

#ifdef __IO_DEFINE
	.SECTION	IO_TMR4,DATA,locate=0x1D2
_IO_TMR4:
__TMR4:	.res.b	2
TMR4	.equ	0x1D2
#endif
	.GLOBAL	_IO_TMR4, __TMR4, TMR4

#ifdef __IO_DEFINE
	.SECTION	IO_TMCSR4,DATA,locate=0x1D6
_IO_TMCSR4:
__tmcsr4:	.res.b	2
TMCSR4	.equ	0x1D6
#endif
	.GLOBAL	_IO_TMCSR4, __tmcsr4, TMCSR4

#ifdef __IO_DEFINE
	.SECTION	IO_TMRLR5,DATA,locate=0x1D8
_IO_TMRLR5:
__TMRLR5:	.res.b	2
TMRLR5	.equ	0x1D8
#endif
	.GLOBAL	_IO_TMRLR5, __TMRLR5, TMRLR5

#ifdef __IO_DEFINE
	.SECTION	IO_TMR5,DATA,locate=0x1DA
_IO_TMR5:
__TMR5:	.res.b	2
TMR5	.equ	0x1DA
#endif
	.GLOBAL	_IO_TMR5, __TMR5, TMR5

#ifdef __IO_DEFINE
	.SECTION	IO_TMCSR5,DATA,locate=0x1DE
_IO_TMCSR5:
__tmcsr5:	.res.b	2
TMCSR5	.equ	0x1DE
#endif
	.GLOBAL	_IO_TMCSR5, __tmcsr5, TMCSR5

#ifdef __IO_DEFINE
	.SECTION	IO_TMRLR6,DATA,locate=0x1E0
_IO_TMRLR6:
__TMRLR6:	.res.b	2
TMRLR6	.equ	0x1E0
#endif
	.GLOBAL	_IO_TMRLR6, __TMRLR6, TMRLR6

#ifdef __IO_DEFINE
	.SECTION	IO_TMR6,DATA,locate=0x1E2
_IO_TMR6:
__TMR6:	.res.b	2
TMR6	.equ	0x1E2
#endif
	.GLOBAL	_IO_TMR6, __TMR6, TMR6

#ifdef __IO_DEFINE
	.SECTION	IO_TMCSR6,DATA,locate=0x1E6
_IO_TMCSR6:
__tmcsr6:	.res.b	2
TMCSR6	.equ	0x1E6
#endif
	.GLOBAL	_IO_TMCSR6, __tmcsr6, TMCSR6

#ifdef __IO_DEFINE
	.SECTION	IO_TMRLR7,DATA,locate=0x1E8
_IO_TMRLR7:
__TMRLR7:	.res.b	2
TMRLR7	.equ	0x1E8
#endif
	.GLOBAL	_IO_TMRLR7, __TMRLR7, TMRLR7

#ifdef __IO_DEFINE
	.SECTION	IO_TMR7,DATA,locate=0x1EA
_IO_TMR7:
__TMR7:	.res.b	2
TMR7	.equ	0x1EA
#endif
	.GLOBAL	_IO_TMR7, __TMR7, TMR7

#ifdef __IO_DEFINE
	.SECTION	IO_TMCSR7,DATA,locate=0x1EE
_IO_TMCSR7:
__tmcsr7:	.res.b	2
TMCSR7	.equ	0x1EE
#endif
	.GLOBAL	_IO_TMCSR7, __tmcsr7, TMCSR7

#ifdef __IO_DEFINE
	.SECTION	IO_TCDT0,DATA,locate=0x1F0
_IO_TCDT0:
__TCDT0:	.res.b	2
TCDT0	.equ	0x1F0
#endif
	.GLOBAL	_IO_TCDT0, __TCDT0, TCDT0

#ifdef __IO_DEFINE
	.SECTION	IO_TCCS0,DATA,locate=0x1F3
_IO_TCCS0:
__tccs0:	.res.b	1
TCCS0	.equ	0x1F3
#endif
	.GLOBAL	_IO_TCCS0, __tccs0, TCCS0

#ifdef __IO_DEFINE
	.SECTION	IO_TCDT1,DATA,locate=0x1F4
_IO_TCDT1:
__TCDT1:	.res.b	2
TCDT1	.equ	0x1F4
#endif
	.GLOBAL	_IO_TCDT1, __TCDT1, TCDT1

#ifdef __IO_DEFINE
	.SECTION	IO_TCCS1,DATA,locate=0x1F7
_IO_TCCS1:
__tccs1:	.res.b	1
TCCS1	.equ	0x1F7
#endif
	.GLOBAL	_IO_TCCS1, __tccs1, TCCS1

#ifdef __IO_DEFINE
	.SECTION	IO_TCDT2,DATA,locate=0x1F8
_IO_TCDT2:
__TCDT2:	.res.b	2
TCDT2	.equ	0x1F8
#endif
	.GLOBAL	_IO_TCDT2, __TCDT2, TCDT2

#ifdef __IO_DEFINE
	.SECTION	IO_TCCS2,DATA,locate=0x1FB
_IO_TCCS2:
__tccs2:	.res.b	1
TCCS2	.equ	0x1FB
#endif
	.GLOBAL	_IO_TCCS2, __tccs2, TCCS2

#ifdef __IO_DEFINE
	.SECTION	IO_TCDT3,DATA,locate=0x1FC
_IO_TCDT3:
__TCDT3:	.res.b	2
TCDT3	.equ	0x1FC
#endif
	.GLOBAL	_IO_TCDT3, __TCDT3, TCDT3

#ifdef __IO_DEFINE
	.SECTION	IO_TCCS3,DATA,locate=0x1FF
_IO_TCCS3:
__tccs3:	.res.b	1
TCCS3	.equ	0x1FF
#endif
	.GLOBAL	_IO_TCCS3, __tccs3, TCCS3

#ifdef __IO_DEFINE
	.SECTION	IO_DMACA0,DATA,locate=0x200
_IO_DMACA0:
__dmaca0:	.res.b	4
DMACA0	.equ	0x200
#endif
	.GLOBAL	_IO_DMACA0, __dmaca0, DMACA0

#ifdef __IO_DEFINE
	.SECTION	IO_DMACB0,DATA,locate=0x204
_IO_DMACB0:
__dmacb0:	.res.b	4
DMACB0	.equ	0x204
#endif
	.GLOBAL	_IO_DMACB0, __dmacb0, DMACB0

#ifdef __IO_DEFINE
	.SECTION	IO_DMACA1,DATA,locate=0x208
_IO_DMACA1:
__dmaca1:	.res.b	4
DMACA1	.equ	0x208
#endif
	.GLOBAL	_IO_DMACA1, __dmaca1, DMACA1

#ifdef __IO_DEFINE
	.SECTION	IO_DMACB1,DATA,locate=0x20C
_IO_DMACB1:
__dmacb1:	.res.b	4
DMACB1	.equ	0x20C
#endif
	.GLOBAL	_IO_DMACB1, __dmacb1, DMACB1

#ifdef __IO_DEFINE
	.SECTION	IO_DMACA2,DATA,locate=0x210
_IO_DMACA2:
__dmaca2:	.res.b	4
DMACA2	.equ	0x210
#endif
	.GLOBAL	_IO_DMACA2, __dmaca2, DMACA2

#ifdef __IO_DEFINE
	.SECTION	IO_DMACB2,DATA,locate=0x214
_IO_DMACB2:
__dmacb2:	.res.b	4
DMACB2	.equ	0x214
#endif
	.GLOBAL	_IO_DMACB2, __dmacb2, DMACB2

#ifdef __IO_DEFINE
	.SECTION	IO_DMACA3,DATA,locate=0x218
_IO_DMACA3:
__dmaca3:	.res.b	4
DMACA3	.equ	0x218
#endif
	.GLOBAL	_IO_DMACA3, __dmaca3, DMACA3

#ifdef __IO_DEFINE
	.SECTION	IO_DMACB3,DATA,locate=0x21C
_IO_DMACB3:
__dmacb3:	.res.b	4
DMACB3	.equ	0x21C
#endif
	.GLOBAL	_IO_DMACB3, __dmacb3, DMACB3

#ifdef __IO_DEFINE
	.SECTION	IO_DMACA4,DATA,locate=0x220
_IO_DMACA4:
__dmaca4:	.res.b	4
DMACA4	.equ	0x220
#endif
	.GLOBAL	_IO_DMACA4, __dmaca4, DMACA4

#ifdef __IO_DEFINE
	.SECTION	IO_DMACB4,DATA,locate=0x224
_IO_DMACB4:
__dmacb4:	.res.b	4
DMACB4	.equ	0x224
#endif
	.GLOBAL	_IO_DMACB4, __dmacb4, DMACB4

#ifdef __IO_DEFINE
	.SECTION	IO_DMACR,DATA,locate=0x240
_IO_DMACR:
__dmacr:	.res.b	1
DMACR	.equ	0x240
#endif
	.GLOBAL	_IO_DMACR, __dmacr, DMACR

#ifdef __IO_DEFINE
	.SECTION	IO_ICS45,DATA,locate=0x2D1
_IO_ICS45:
__ics45:	.res.b	1
ICS45	.equ	0x2D1
#endif
	.GLOBAL	_IO_ICS45, __ics45, ICS45

#ifdef __IO_DEFINE
	.SECTION	IO_ICS67,DATA,locate=0x2D3
_IO_ICS67:
__ics67:	.res.b	1
ICS67	.equ	0x2D3
#endif
	.GLOBAL	_IO_ICS67, __ics67, ICS67

#ifdef __IO_DEFINE
	.SECTION	IO_IPCP4,DATA,locate=0x2D4
_IO_IPCP4:
__IPCP4:	.res.b	2
IPCP4	.equ	0x2D4
#endif
	.GLOBAL	_IO_IPCP4, __IPCP4, IPCP4

#ifdef __IO_DEFINE
	.SECTION	IO_IPCP5,DATA,locate=0x2D6
_IO_IPCP5:
__IPCP5:	.res.b	2
IPCP5	.equ	0x2D6
#endif
	.GLOBAL	_IO_IPCP5, __IPCP5, IPCP5

#ifdef __IO_DEFINE
	.SECTION	IO_IPCP6,DATA,locate=0x2D8
_IO_IPCP6:
__IPCP6:	.res.b	2
IPCP6	.equ	0x2D8
#endif
	.GLOBAL	_IO_IPCP6, __IPCP6, IPCP6

#ifdef __IO_DEFINE
	.SECTION	IO_IPCP7,DATA,locate=0x2DA
_IO_IPCP7:
__IPCP7:	.res.b	2
IPCP7	.equ	0x2DA
#endif
	.GLOBAL	_IO_IPCP7, __IPCP7, IPCP7

#ifdef __IO_DEFINE
	.SECTION	IO_OCS45,DATA,locate=0x2DC
_IO_OCS45:
__ocs45:	.res.b	2
OCS45	.equ	0x2DC
#endif
	.GLOBAL	_IO_OCS45, __ocs45, OCS45

#ifdef __IO_DEFINE
	.SECTION	IO_OCCP4,DATA,locate=0x2E0
_IO_OCCP4:
__OCCP4:	.res.b	2
OCCP4	.equ	0x2E0
#endif
	.GLOBAL	_IO_OCCP4, __OCCP4, OCCP4

#ifdef __IO_DEFINE
	.SECTION	IO_OCCP5,DATA,locate=0x2E2
_IO_OCCP5:
__OCCP5:	.res.b	2
OCCP5	.equ	0x2E2
#endif
	.GLOBAL	_IO_OCCP5, __OCCP5, OCCP5

#ifdef __IO_DEFINE
	.SECTION	IO_TCDT4,DATA,locate=0x2F0
_IO_TCDT4:
__TCDT4:	.res.b	2
TCDT4	.equ	0x2F0
#endif
	.GLOBAL	_IO_TCDT4, __TCDT4, TCDT4

#ifdef __IO_DEFINE
	.SECTION	IO_TCCS4,DATA,locate=0x2F3
_IO_TCCS4:
__tccs4:	.res.b	1
TCCS4	.equ	0x2F3
#endif
	.GLOBAL	_IO_TCCS4, __tccs4, TCCS4

#ifdef __IO_DEFINE
	.SECTION	IO_TCDT5,DATA,locate=0x2F4
_IO_TCDT5:
__TCDT5:	.res.b	2
TCDT5	.equ	0x2F4
#endif
	.GLOBAL	_IO_TCDT5, __TCDT5, TCDT5

#ifdef __IO_DEFINE
	.SECTION	IO_TCCS5,DATA,locate=0x2F7
_IO_TCCS5:
__tccs5:	.res.b	1
TCCS5	.equ	0x2F7
#endif
	.GLOBAL	_IO_TCCS5, __tccs5, TCCS5

#ifdef __IO_DEFINE
	.SECTION	IO_TCDT6,DATA,locate=0x2F8
_IO_TCDT6:
__TCDT6:	.res.b	2
TCDT6	.equ	0x2F8
#endif
	.GLOBAL	_IO_TCDT6, __TCDT6, TCDT6

#ifdef __IO_DEFINE
	.SECTION	IO_TCCS6,DATA,locate=0x2FB
_IO_TCCS6:
__tccs6:	.res.b	1
TCCS6	.equ	0x2FB
#endif
	.GLOBAL	_IO_TCCS6, __tccs6, TCCS6

#ifdef __IO_DEFINE
	.SECTION	IO_TCDT7,DATA,locate=0x2FC
_IO_TCDT7:
__TCDT7:	.res.b	2
TCDT7	.equ	0x2FC
#endif
	.GLOBAL	_IO_TCDT7, __TCDT7, TCDT7

#ifdef __IO_DEFINE
	.SECTION	IO_TCCS7,DATA,locate=0x2FF
_IO_TCCS7:
__tccs7:	.res.b	1
TCCS7	.equ	0x2FF
#endif
	.GLOBAL	_IO_TCCS7, __tccs7, TCCS7

#ifdef __IO_DEFINE
	.SECTION	IO_ROMS,DATA,locate=0x390
_IO_ROMS:
__ROMS:	.res.b	2
ROMS	.equ	0x390
#endif
	.GLOBAL	_IO_ROMS, __ROMS, ROMS

#ifdef __IO_DEFINE
	.SECTION	IO_BSD0,DATA,locate=0x3F0
_IO_BSD0:
__BSD0:	.res.b	4
BSD0	.equ	0x3F0
#endif
	.GLOBAL	_IO_BSD0, __BSD0, BSD0

#ifdef __IO_DEFINE
	.SECTION	IO_BSD1,DATA,locate=0x3F4
_IO_BSD1:
__BSD1:	.res.b	4
BSD1	.equ	0x3F4
#endif
	.GLOBAL	_IO_BSD1, __BSD1, BSD1

#ifdef __IO_DEFINE
	.SECTION	IO_BSDC,DATA,locate=0x3F8
_IO_BSDC:
__BSDC:	.res.b	4
BSDC	.equ	0x3F8
#endif
	.GLOBAL	_IO_BSDC, __BSDC, BSDC

#ifdef __IO_DEFINE
	.SECTION	IO_BSRR,DATA,locate=0x3FC
_IO_BSRR:
__BSRR:	.res.b	4
BSRR	.equ	0x3FC
#endif
	.GLOBAL	_IO_BSRR, __BSRR, BSRR

#ifdef __IO_DEFINE
	.SECTION	IO_ICR,DATA,locate=0x440
_IO_ICR:	.res.b	0
_IO_ICR_0:	.res.b	1
_IO_ICR_1:	.res.b	1
_IO_ICR_2:	.res.b	1
_IO_ICR_3:	.res.b	1
_IO_ICR_4:	.res.b	1
_IO_ICR_5:	.res.b	1
_IO_ICR_6:	.res.b	1
_IO_ICR_7:	.res.b	1
_IO_ICR_8:	.res.b	1
_IO_ICR_9:	.res.b	1
_IO_ICR_10:	.res.b	1
_IO_ICR_11:	.res.b	1
_IO_ICR_12:	.res.b	1
_IO_ICR_13:	.res.b	1
_IO_ICR_14:	.res.b	1
_IO_ICR_15:	.res.b	1
_IO_ICR_16:	.res.b	1
_IO_ICR_17:	.res.b	1
_IO_ICR_18:	.res.b	1
_IO_ICR_19:	.res.b	1
_IO_ICR_20:	.res.b	1
_IO_ICR_21:	.res.b	1
_IO_ICR_22:	.res.b	1
_IO_ICR_23:	.res.b	1
_IO_ICR_24:	.res.b	1
_IO_ICR_25:	.res.b	1
_IO_ICR_26:	.res.b	1
_IO_ICR_27:	.res.b	1
_IO_ICR_28:	.res.b	1
_IO_ICR_29:	.res.b	1
_IO_ICR_30:	.res.b	1
_IO_ICR_31:	.res.b	1
_IO_ICR_32:	.res.b	1
_IO_ICR_33:	.res.b	1
_IO_ICR_34:	.res.b	1
_IO_ICR_35:	.res.b	1
_IO_ICR_36:	.res.b	1
_IO_ICR_37:	.res.b	1
_IO_ICR_38:	.res.b	1
_IO_ICR_39:	.res.b	1
_IO_ICR_40:	.res.b	1
_IO_ICR_41:	.res.b	1
_IO_ICR_42:	.res.b	1
_IO_ICR_43:	.res.b	1
_IO_ICR_44:	.res.b	1
_IO_ICR_45:	.res.b	1
_IO_ICR_46:	.res.b	1
_IO_ICR_47:	.res.b	1
_IO_ICR_48:	.res.b	1
_IO_ICR_49:	.res.b	1
_IO_ICR_50:	.res.b	1
_IO_ICR_51:	.res.b	1
_IO_ICR_52:	.res.b	1
_IO_ICR_53:	.res.b	1
_IO_ICR_54:	.res.b	1
_IO_ICR_55:	.res.b	1
_IO_ICR_56:	.res.b	1
_IO_ICR_57:	.res.b	1
_IO_ICR_58:	.res.b	1
_IO_ICR_59:	.res.b	1
_IO_ICR_60:	.res.b	1
_IO_ICR_61:	.res.b	1
_IO_ICR_62:	.res.b	1
_IO_ICR_63:	.res.b	1
#endif
	.GLOBAL	_IO_ICR
	.GLOBAL	_IO_ICR_0
	.GLOBAL	_IO_ICR_1
	.GLOBAL	_IO_ICR_2
	.GLOBAL	_IO_ICR_3
	.GLOBAL	_IO_ICR_4
	.GLOBAL	_IO_ICR_5
	.GLOBAL	_IO_ICR_6
	.GLOBAL	_IO_ICR_7
	.GLOBAL	_IO_ICR_8
	.GLOBAL	_IO_ICR_9
	.GLOBAL	_IO_ICR_10
	.GLOBAL	_IO_ICR_11
	.GLOBAL	_IO_ICR_12
	.GLOBAL	_IO_ICR_13
	.GLOBAL	_IO_ICR_14
	.GLOBAL	_IO_ICR_15
	.GLOBAL	_IO_ICR_16
	.GLOBAL	_IO_ICR_17
	.GLOBAL	_IO_ICR_18
	.GLOBAL	_IO_ICR_19
	.GLOBAL	_IO_ICR_20
	.GLOBAL	_IO_ICR_21
	.GLOBAL	_IO_ICR_22
	.GLOBAL	_IO_ICR_23
	.GLOBAL	_IO_ICR_24
	.GLOBAL	_IO_ICR_25
	.GLOBAL	_IO_ICR_26
	.GLOBAL	_IO_ICR_27
	.GLOBAL	_IO_ICR_28
	.GLOBAL	_IO_ICR_29
	.GLOBAL	_IO_ICR_30
	.GLOBAL	_IO_ICR_31
	.GLOBAL	_IO_ICR_32
	.GLOBAL	_IO_ICR_33
	.GLOBAL	_IO_ICR_34
	.GLOBAL	_IO_ICR_35
	.GLOBAL	_IO_ICR_36
	.GLOBAL	_IO_ICR_37
	.GLOBAL	_IO_ICR_38
	.GLOBAL	_IO_ICR_39
	.GLOBAL	_IO_ICR_40
	.GLOBAL	_IO_ICR_41
	.GLOBAL	_IO_ICR_42
	.GLOBAL	_IO_ICR_43
	.GLOBAL	_IO_ICR_44
	.GLOBAL	_IO_ICR_45
	.GLOBAL	_IO_ICR_46
	.GLOBAL	_IO_ICR_47
	.GLOBAL	_IO_ICR_48
	.GLOBAL	_IO_ICR_49
	.GLOBAL	_IO_ICR_50
	.GLOBAL	_IO_ICR_51
	.GLOBAL	_IO_ICR_52
	.GLOBAL	_IO_ICR_53
	.GLOBAL	_IO_ICR_54
	.GLOBAL	_IO_ICR_55
	.GLOBAL	_IO_ICR_56
	.GLOBAL	_IO_ICR_57
	.GLOBAL	_IO_ICR_58
	.GLOBAL	_IO_ICR_59
	.GLOBAL	_IO_ICR_60
	.GLOBAL	_IO_ICR_61
	.GLOBAL	_IO_ICR_62
	.GLOBAL	_IO_ICR_63


#ifdef __IO_DEFINE
	.SECTION	IO_CLK,DATA,locate=0x480
_IO_CLK:	.res.b	0
_IO_CLK_IO_RSRR:	.res.b	1
_IO_CLK_IO_STCR:	.res.b	1
_IO_CLK_IO_TBCR:	.res.b	1
_IO_CLK_IO_CTBR:	.res.b	1
_IO_CLK_IO_CLKR:	.res.b	1
_IO_CLK_IO_WPR:	.res.b	1
_IO_CLK_IO_DIVR0:	.res.b	1
_IO_CLK_IO_DIVR1:	.res.b	1
#endif
	.GLOBAL	_IO_CLK
	.GLOBAL	_IO_CLK_IO_RSRR
	.GLOBAL	_IO_CLK_IO_STCR
	.GLOBAL	_IO_CLK_IO_TBCR
	.GLOBAL	_IO_CLK_IO_CTBR
	.GLOBAL	_IO_CLK_IO_CLKR
	.GLOBAL	_IO_CLK_IO_WPR
	.GLOBAL	_IO_CLK_IO_DIVR0
	.GLOBAL	_IO_CLK_IO_DIVR1

#ifdef __IO_DEFINE
	.SECTION	IO_PLL,DATA,locate=0x48C
_IO_PLL:	.res.b	0
_IO_PLL_IO_DIVM:	.res.b	1
_IO_PLL_IO_DIVN:	.res.b	1
_IO_PLL_IO_DIVG:	.res.b	1
_IO_PLL_IO_MULG:	.res.b	1
_IO_PLL_IO_CTRL:	.res.b	1
_IO_PLL_IO_RESV1:	.res.b	1
_IO_PLL_IO_RESV2:	.res.b	1
_IO_PLL_IO_RESV3:	.res.b	1
#endif
	.GLOBAL	_IO_PLL
	.GLOBAL	_IO_PLL_IO_DIVM
	.GLOBAL	_IO_PLL_IO_DIVN
	.GLOBAL	_IO_PLL_IO_DIVG
	.GLOBAL	_IO_PLL_IO_MULG
	.GLOBAL	_IO_PLL_IO_CTRL
	.GLOBAL	_IO_PLL_IO_RESV1
	.GLOBAL	_IO_PLL_IO_RESV2
	.GLOBAL	_IO_PLL_IO_RESV3

#ifdef __IO_DEFINE
	.SECTION	IO_OSCC1,DATA,locate=0x494
_IO_OSCC1:
__OSCC1:	.res.b	1
OSCC1	.equ	0x494
#endif
	.GLOBAL	_IO_OSCC1, __OSCC1, OSCC1

#ifdef __IO_DEFINE
	.SECTION	IO_OSCS1,DATA,locate=0x495
_IO_OSCS1:
__OSCS1:	.res.b	1
OSCS1	.equ	0x495
#endif
	.GLOBAL	_IO_OSCS1, __OSCS1, OSCS1

#ifdef __IO_DEFINE
	.SECTION	IO_OSCC2,DATA,locate=0x496
_IO_OSCC2:
__OSCC2:	.res.b	1
OSCC2	.equ	0x496
#endif
	.GLOBAL	_IO_OSCC2, __OSCC2, OSCC2

#ifdef __IO_DEFINE
	.SECTION	IO_OSCS2,DATA,locate=0x497
_IO_OSCS2:
__OSCS2:	.res.b	1
OSCS2	.equ	0x497
#endif
	.GLOBAL	_IO_OSCS2, __OSCS2, OSCS2

#ifdef __IO_DEFINE
	.SECTION	IO_PORTEN,DATA,locate=0x498
_IO_PORTEN:
__porten:	.res.b	1
PORTEN	.equ	0x498
#endif
	.GLOBAL	_IO_PORTEN, __porten, PORTEN

#ifdef __IO_DEFINE
	.SECTION	IO_WT,DATA,locate=0x4A0
_IO_WT:	.res.b	0
_IO_WT_IO_RESV1:	.res.b	1
_IO_WT_IO_WTCER:	.res.b	1
_IO_WT_IO_WTCRH:	.res.b	1
_IO_WT_IO_WTCRL:	.res.b	1
_IO_WT_IO_RESV2:	.res.b	1
_IO_WT_IO_WTBRH:	.res.b	1
_IO_WT_IO_WTBRM:	.res.b	1
_IO_WT_IO_WTBRL:	.res.b	1
_IO_WT_IO_WTHR:	.res.b	1
_IO_WT_IO_WTMR:	.res.b	1
_IO_WT_IO_WTSR:	.res.b	1
_IO_WT_IO_RESV3:	.res.b	1
#endif
	.GLOBAL	_IO_WT
	.GLOBAL	_IO_WT_IO_RESV1
	.GLOBAL	_IO_WT_IO_WTCER
	.GLOBAL	_IO_WT_IO_WTCRH
	.GLOBAL	_IO_WT_IO_WTCRL
	.GLOBAL	_IO_WT_IO_RESV2
	.GLOBAL	_IO_WT_IO_WTBRH
	.GLOBAL	_IO_WT_IO_WTBRM
	.GLOBAL	_IO_WT_IO_WTBRL
	.GLOBAL	_IO_WT_IO_WTHR
	.GLOBAL	_IO_WT_IO_WTMR
	.GLOBAL	_IO_WT_IO_WTSR
	.GLOBAL	_IO_WT_IO_RESV3

#ifdef __IO_DEFINE
	.SECTION	IO_CSS,DATA,locate=0x4AC
_IO_CSS:	.res.b	0
_IO_CSS_IO_CSVTR:	.res.b	1
_IO_CSS_IO_CSVCR:	.res.b	1
_IO_CSS_IO_CSCFG:	.res.b	1
_IO_CSS_IO_CMCFG:	.res.b	1
#endif
	.GLOBAL	_IO_CSS
	.GLOBAL	_IO_CSS_IO_CSVTR
	.GLOBAL	_IO_CSS_IO_CSVCR
	.GLOBAL	_IO_CSS_IO_CSCFG
	.GLOBAL	_IO_CSS_IO_CMCFG

#ifdef __IO_DEFINE
	.SECTION	IO_CUSO,DATA,locate=0x4B0
_IO_CUSO:	.res.b	0
_IO_CUSO_IO_CUCR:	.res.b	2
_IO_CUSO_IO_CUTD:	.res.b	2
_IO_CUSO_IO_CUTR1:	.res.b	2
_IO_CUSO_IO_CUTR2:	.res.b	2
#endif
	.GLOBAL	_IO_CUSO
	.GLOBAL	_IO_CUSO_IO_CUCR
	.GLOBAL	_IO_CUSO_IO_CUTD
	.GLOBAL	_IO_CUSO_IO_CUTR1
	.GLOBAL	_IO_CUSO_IO_CUTR2

#ifdef __IO_DEFINE
	.SECTION	IO_CM,DATA,locate=0x4B8
_IO_CM:	.res.b	0
_IO_CM_IO_CMPR:	.res.b	2
_IO_CM_IO_RESV1:	.res.b	1
_IO_CM_IO_CMCR:	.res.b	1
_IO_CM_IO_CMT1:	.res.b	2
_IO_CM_IO_CMT2:	.res.b	2
#endif
	.GLOBAL	_IO_CM
	.GLOBAL	_IO_CM_IO_CMPR
	.GLOBAL	_IO_CM_IO_RESV1
	.GLOBAL	_IO_CM_IO_CMCR
	.GLOBAL	_IO_CM_IO_CMT1
	.GLOBAL	_IO_CM_IO_CMT2

#ifdef __IO_DEFINE
	.SECTION	IO_CANPRE,DATA,locate=0x4C0
_IO_CANPRE:
__canpre:	.res.b	1
CANPRE	.equ	0x4C0
#endif
	.GLOBAL	_IO_CANPRE, __canpre, CANPRE

#ifdef __IO_DEFINE
	.SECTION	IO_CANCKD,DATA,locate=0x4C1
_IO_CANCKD:
__CANCKD:	.res.b	1
CANCKD	.equ	0x4C1
#endif
	.GLOBAL	_IO_CANCKD, __CANCKD, CANCKD

#ifdef __IO_DEFINE
	.SECTION	IO_LVD,DATA,locate=0x4C4
_IO_LVD:	.res.b	0
_IO_LVD_IO_LVSEL:	.res.b	1
_IO_LVD_IO_LVDET:	.res.b	1
_IO_LVD_IO_HWWDE:	.res.b	1
_IO_LVD_IO_HWWD:	.res.b	1
#endif
	.GLOBAL	_IO_LVD
	.GLOBAL	_IO_LVD_IO_LVSEL
	.GLOBAL	_IO_LVD_IO_LVDET
	.GLOBAL	_IO_LVD_IO_HWWDE
	.GLOBAL	_IO_LVD_IO_HWWD

#ifdef __IO_DEFINE
	.SECTION	IO_OST,DATA,locate=0x4C8
_IO_OST:	.res.b	0
_IO_OST_IO_OSCRH:	.res.b	1
_IO_OST_IO_RESV1:	.res.b	1
_IO_OST_IO_WPCRH:	.res.b	1
_IO_OST_IO_RESV2:	.res.b	1
#endif
	.GLOBAL	_IO_OST
	.GLOBAL	_IO_OST_IO_OSCRH
	.GLOBAL	_IO_OST_IO_RESV1
	.GLOBAL	_IO_OST_IO_WPCRH
	.GLOBAL	_IO_OST_IO_RESV2

#ifdef __IO_DEFINE
	.SECTION	IO_OSC,DATA,locate=0x4CC
_IO_OSC:	.res.b	0
_IO_OSC_IO_OSCCR:	.res.b	1
_IO_OSC_IO_RESV1:	.res.b	1
_IO_OSC_IO_RESV2:	.res.b	1
_IO_OSC_IO_RESV3:	.res.b	1
#endif
	.GLOBAL	_IO_OSC
	.GLOBAL	_IO_OSC_IO_OSCCR
	.GLOBAL	_IO_OSC_IO_RESV1
	.GLOBAL	_IO_OSC_IO_RESV2
	.GLOBAL	_IO_OSC_IO_RESV3

#ifdef __IO_DEFINE
	.SECTION	IO_PLL2,DATA,locate=0x4DC
_IO_PLL2:	.res.b	0
_IO_PLL2_IO_DIVM:	.res.b	1
_IO_PLL2_IO_DIVN:	.res.b	1
_IO_PLL2_IO_DIVG:	.res.b	1
_IO_PLL2_IO_MULG:	.res.b	1
_IO_PLL2_IO_CTRL:	.res.b	1
_IO_PLL2_IO_RESV1:	.res.b	1
_IO_PLL2_IO_CLKR2:	.res.b	1
_IO_PLL2_IO_RESV2:	.res.b	1
#endif
	.GLOBAL	_IO_PLL2
	.GLOBAL	_IO_PLL2_IO_DIVM
	.GLOBAL	_IO_PLL2_IO_DIVN
	.GLOBAL	_IO_PLL2_IO_DIVG
	.GLOBAL	_IO_PLL2_IO_MULG
	.GLOBAL	_IO_PLL2_IO_CTRL
	.GLOBAL	_IO_PLL2_IO_RESV1
	.GLOBAL	_IO_PLL2_IO_CLKR2
	.GLOBAL	_IO_PLL2_IO_RESV2

#ifdef __IO_DEFINE
	.SECTION	IO_IOS,DATA,locate=0xC03
_IO_IOS:
__IOS:	.res.b	1
IOS	.equ	0xC03
#endif
	.GLOBAL	_IO_IOS, __IOS, IOS

#ifdef __IO_DEFINE
	.SECTION	IO_PORT2,DATA,locate=0xD00
_IO_PORT2:	.res.b	0
_IO_PORT2_IO_RESV000:	.res.b	1
_IO_PORT2_IO_RESV001:	.res.b	1
_IO_PORT2_IO_RESV002:	.res.b	1
_IO_PORT2_IO_RESV003:	.res.b	1
_IO_PORT2_IO_RESV004:	.res.b	1
_IO_PORT2_IO_RESV005:	.res.b	1
_IO_PORT2_IO_RESV006:	.res.b	1
_IO_PORT2_IO_RESV007:	.res.b	1
_IO_PORT2_IO_RESV008:	.res.b	1
_IO_PORT2_IO_RESV009:	.res.b	1
_IO_PORT2_IO_RESV010:	.res.b	1
_IO_PORT2_IO_RESV011:	.res.b	1
_IO_PORT2_IO_RESV012:	.res.b	1
_IO_PORT2_IO_RESV013:	.res.b	1
_IO_PORT2_IO_PDRD14:	.res.b	1
_IO_PORT2_IO_PDRD15:	.res.b	1
_IO_PORT2_IO_PDRD16:	.res.b	1
_IO_PORT2_IO_PDRD17:	.res.b	1
_IO_PORT2_IO_PDRD18:	.res.b	1
_IO_PORT2_IO_PDRD19:	.res.b	1
_IO_PORT2_IO_RESV020:	.res.b	1
_IO_PORT2_IO_RESV021:	.res.b	1
_IO_PORT2_IO_PDRD22:	.res.b	1
_IO_PORT2_IO_PDRD23:	.res.b	1
_IO_PORT2_IO_PDRD24:	.res.b	1
_IO_PORT2_IO_RESV025:	.res.b	1
_IO_PORT2_IO_RESV026:	.res.b	1
_IO_PORT2_IO_PDRD27:	.res.b	1
_IO_PORT2_IO_PDRD28:	.res.b	1
_IO_PORT2_IO_PDRD29:	.res.b	1
_IO_PORT2_IO_RESV030:	.res.b	1
_IO_PORT2_IO_PDRD31:	.res.b	1
_IO_PORT2_IO_RESV32	.res.b	46
_IO_PORT2_IO_DDR14:	.res.b	1
_IO_PORT2_IO_DDR15:	.res.b	1
_IO_PORT2_IO_DDR16:	.res.b	1
_IO_PORT2_IO_DDR17:	.res.b	1
_IO_PORT2_IO_DDR18:	.res.b	1
_IO_PORT2_IO_DDR19:	.res.b	1
_IO_PORT2_IO_RESV084:	.res.b	1
_IO_PORT2_IO_RESV085:	.res.b	1
_IO_PORT2_IO_DDR22:	.res.b	1
_IO_PORT2_IO_DDR23:	.res.b	1
_IO_PORT2_IO_DDR24:	.res.b	1
_IO_PORT2_IO_RESV089:	.res.b	1
_IO_PORT2_IO_RESV090:	.res.b	1
_IO_PORT2_IO_DDR27:	.res.b	1
_IO_PORT2_IO_DDR28:	.res.b	1
_IO_PORT2_IO_DDR29:	.res.b	1
_IO_PORT2_IO_RESV94:	.res.b	1
_IO_PORT2_IO_DDR31:	.res.b	1
_IO_PORT2_IO_RESV96	.res.b	46
_IO_PORT2_IO_PFR14:	.res.b	1
_IO_PORT2_IO_PFR15:	.res.b	1
_IO_PORT2_IO_PFR16:	.res.b	1
_IO_PORT2_IO_PFR17:	.res.b	1
_IO_PORT2_IO_PFR18:	.res.b	1
_IO_PORT2_IO_PFR19:	.res.b	1
_IO_PORT2_IO_RESV148:	.res.b	1
_IO_PORT2_IO_RESV149:	.res.b	1
_IO_PORT2_IO_PFR22:	.res.b	1
_IO_PORT2_IO_PFR23:	.res.b	1
_IO_PORT2_IO_PFR24:	.res.b	1
_IO_PORT2_IO_RESV153:	.res.b	1
_IO_PORT2_IO_RESV154:	.res.b	1
_IO_PORT2_IO_PFR27:	.res.b	1
_IO_PORT2_IO_PFR28:	.res.b	1
_IO_PORT2_IO_PFR29:	.res.b	1
_IO_PORT2_IO_RESV158:	.res.b	1
_IO_PORT2_IO_PFR31:	.res.b	1
_IO_PORT2_IO_RESV160	.res.b	46
_IO_PORT2_IO_EPFR14:	.res.b	1
_IO_PORT2_IO_EPFR15:	.res.b	1
_IO_PORT2_IO_EPFR16:	.res.b	1
_IO_PORT2_IO_EPFR17:	.res.b	1
_IO_PORT2_IO_EPFR18:	.res.b	1
_IO_PORT2_IO_EPFR19:	.res.b	1
_IO_PORT2_IO_RESV212:	.res.b	1
_IO_PORT2_IO_RESV213:	.res.b	1
_IO_PORT2_IO_EPFR22:	.res.b	1
_IO_PORT2_IO_EPFR23:	.res.b	1
_IO_PORT2_IO_EPFR24:	.res.b	1
_IO_PORT2_IO_RESV217:	.res.b	1
_IO_PORT2_IO_RESV218:	.res.b	1
_IO_PORT2_IO_EPFR27:	.res.b	1
_IO_PORT2_IO_EPFR28:	.res.b	1
_IO_PORT2_IO_EPFR29:	.res.b	1
_IO_PORT2_IO_RESV222:	.res.b	1
_IO_PORT2_IO_EPFR31:	.res.b	1
_IO_PORT2_IO_RESV224	.res.b	46
_IO_PORT2_IO_PODR14:	.res.b	1
_IO_PORT2_IO_PODR15:	.res.b	1
_IO_PORT2_IO_PODR16:	.res.b	1
_IO_PORT2_IO_PODR17:	.res.b	1
_IO_PORT2_IO_PODR18:	.res.b	1
_IO_PORT2_IO_PODR19:	.res.b	1
_IO_PORT2_IO_RESV276:	.res.b	1
_IO_PORT2_IO_RESV277:	.res.b	1
_IO_PORT2_IO_PODR22:	.res.b	1
_IO_PORT2_IO_PODR23:	.res.b	1
_IO_PORT2_IO_PODR24:	.res.b	1
_IO_PORT2_IO_RESV281:	.res.b	1
_IO_PORT2_IO_RESV282:	.res.b	1
_IO_PORT2_IO_PODR27:	.res.b	1
_IO_PORT2_IO_PODR28:	.res.b	1
_IO_PORT2_IO_PODR29:	.res.b	1
_IO_PORT2_IO_RESV286:	.res.b	1
_IO_PORT2_IO_PODR31:	.res.b	1
_IO_PORT2_IO_RESV288	.res.b	46
_IO_PORT2_IO_PILR14:	.res.b	1
_IO_PORT2_IO_PILR15:	.res.b	1
_IO_PORT2_IO_PILR16:	.res.b	1
_IO_PORT2_IO_PILR17:	.res.b	1
_IO_PORT2_IO_PILR18:	.res.b	1
_IO_PORT2_IO_PILR19:	.res.b	1
_IO_PORT2_IO_RESV340:	.res.b	1
_IO_PORT2_IO_RESV341:	.res.b	1
_IO_PORT2_IO_PILR22:	.res.b	1
_IO_PORT2_IO_PILR23:	.res.b	1
_IO_PORT2_IO_PILR24:	.res.b	1
_IO_PORT2_IO_RESV345:	.res.b	1
_IO_PORT2_IO_RESV346:	.res.b	1
_IO_PORT2_IO_PILR27:	.res.b	1
_IO_PORT2_IO_PILR28:	.res.b	1
_IO_PORT2_IO_PILR29:	.res.b	1
_IO_PORT2_IO_RESV350:	.res.b	1
_IO_PORT2_IO_PILR31:	.res.b	1
_IO_PORT2_IO_RESV352	.res.b	46
_IO_PORT2_IO_EPILR14:	.res.b	1
_IO_PORT2_IO_EPILR15:	.res.b	1
_IO_PORT2_IO_EPILR16:	.res.b	1
_IO_PORT2_IO_EPILR17:	.res.b	1
_IO_PORT2_IO_EPILR18:	.res.b	1
_IO_PORT2_IO_EPILR19:	.res.b	1
_IO_PORT2_IO_RESV404:	.res.b	1
_IO_PORT2_IO_RESV405:	.res.b	1
_IO_PORT2_IO_EPILR22:	.res.b	1
_IO_PORT2_IO_EPILR23:	.res.b	1
_IO_PORT2_IO_EPILR24:	.res.b	1
_IO_PORT2_IO_RESV409:	.res.b	1
_IO_PORT2_IO_RESV410:	.res.b	1
_IO_PORT2_IO_EPILR27:	.res.b	1
_IO_PORT2_IO_EPILR28:	.res.b	1
_IO_PORT2_IO_EPILR29:	.res.b	1
_IO_PORT2_IO_RESV414:	.res.b	1
_IO_PORT2_IO_EPILR31:	.res.b	1
_IO_PORT2_IO_RESV416	.res.b	46
_IO_PORT2_IO_PPER14:	.res.b	1
_IO_PORT2_IO_PPER15:	.res.b	1
_IO_PORT2_IO_PPER16:	.res.b	1
_IO_PORT2_IO_PPER17:	.res.b	1
_IO_PORT2_IO_PPER18:	.res.b	1
_IO_PORT2_IO_PPER19:	.res.b	1
_IO_PORT2_IO_RESV468:	.res.b	1
_IO_PORT2_IO_RESV469:	.res.b	1
_IO_PORT2_IO_PPER22:	.res.b	1
_IO_PORT2_IO_PPER23:	.res.b	1
_IO_PORT2_IO_PPER24:	.res.b	1
_IO_PORT2_IO_RESV473:	.res.b	1
_IO_PORT2_IO_RESV474:	.res.b	1
_IO_PORT2_IO_PPER27:	.res.b	1
_IO_PORT2_IO_PPER28:	.res.b	1
_IO_PORT2_IO_PPER29:	.res.b	1
_IO_PORT2_IO_RESV478:	.res.b	1
_IO_PORT2_IO_PPER31:	.res.b	1
_IO_PORT2_IO_RESV480	.res.b	46
_IO_PORT2_IO_PPCR14:	.res.b	1
_IO_PORT2_IO_PPCR15:	.res.b	1
_IO_PORT2_IO_PPCR16:	.res.b	1
_IO_PORT2_IO_PPCR17:	.res.b	1
_IO_PORT2_IO_PPCR18:	.res.b	1
_IO_PORT2_IO_PPCR19:	.res.b	1
_IO_PORT2_IO_RESV532:	.res.b	1
_IO_PORT2_IO_RESV533:	.res.b	1
_IO_PORT2_IO_PPCR22:	.res.b	1
_IO_PORT2_IO_PPCR23:	.res.b	1
_IO_PORT2_IO_PPCR24:	.res.b	1
_IO_PORT2_IO_RESV537:	.res.b	1
_IO_PORT2_IO_RESV538:	.res.b	1
_IO_PORT2_IO_PPCR27:	.res.b	1
_IO_PORT2_IO_PPCR28:	.res.b	1
_IO_PORT2_IO_PPCR29:	.res.b	1
_IO_PORT2_IO_RESV542:	.res.b	1
_IO_PORT2_IO_PPCR31:	.res.b	1
#endif
	.GLOBAL	_IO_PORT2
	.GLOBAL	_IO_PORT2_IO_RESV000
	.GLOBAL	_IO_PORT2_IO_RESV001
	.GLOBAL	_IO_PORT2_IO_RESV002
	.GLOBAL	_IO_PORT2_IO_RESV003
	.GLOBAL	_IO_PORT2_IO_RESV004
	.GLOBAL	_IO_PORT2_IO_RESV005
	.GLOBAL	_IO_PORT2_IO_RESV006
	.GLOBAL	_IO_PORT2_IO_RESV007
	.GLOBAL	_IO_PORT2_IO_RESV008
	.GLOBAL	_IO_PORT2_IO_RESV009
	.GLOBAL	_IO_PORT2_IO_RESV010
	.GLOBAL	_IO_PORT2_IO_RESV011
	.GLOBAL	_IO_PORT2_IO_RESV012
	.GLOBAL	_IO_PORT2_IO_RESV013
	.GLOBAL	_IO_PORT2_IO_PDRD14
	.GLOBAL	_IO_PORT2_IO_PDRD15
	.GLOBAL	_IO_PORT2_IO_PDRD16
	.GLOBAL	_IO_PORT2_IO_PDRD17
	.GLOBAL	_IO_PORT2_IO_PDRD18
	.GLOBAL	_IO_PORT2_IO_PDRD19
	.GLOBAL	_IO_PORT2_IO_RESV020
	.GLOBAL	_IO_PORT2_IO_RESV021
	.GLOBAL	_IO_PORT2_IO_PDRD22
	.GLOBAL	_IO_PORT2_IO_PDRD23
	.GLOBAL	_IO_PORT2_IO_PDRD24
	.GLOBAL	_IO_PORT2_IO_RESV025
	.GLOBAL	_IO_PORT2_IO_RESV026
	.GLOBAL	_IO_PORT2_IO_PDRD27
	.GLOBAL	_IO_PORT2_IO_PDRD28
	.GLOBAL	_IO_PORT2_IO_PDRD29
	.GLOBAL	_IO_PORT2_IO_RESV030
	.GLOBAL	_IO_PORT2_IO_PDRD31
	.GLOBAL	_IO_PORT2_IO_RESV32
	.GLOBAL	_IO_PORT2_IO_RESV32_0
	.GLOBAL	_IO_PORT2_IO_RESV32_1
	.GLOBAL	_IO_PORT2_IO_RESV32_2
	.GLOBAL	_IO_PORT2_IO_RESV32_3
	.GLOBAL	_IO_PORT2_IO_RESV32_4
	.GLOBAL	_IO_PORT2_IO_RESV32_5
	.GLOBAL	_IO_PORT2_IO_RESV32_6
	.GLOBAL	_IO_PORT2_IO_RESV32_7
	.GLOBAL	_IO_PORT2_IO_RESV32_8
	.GLOBAL	_IO_PORT2_IO_RESV32_9
	.GLOBAL	_IO_PORT2_IO_RESV32_10
	.GLOBAL	_IO_PORT2_IO_RESV32_11
	.GLOBAL	_IO_PORT2_IO_RESV32_12
	.GLOBAL	_IO_PORT2_IO_RESV32_13
	.GLOBAL	_IO_PORT2_IO_RESV32_14
	.GLOBAL	_IO_PORT2_IO_RESV32_15
	.GLOBAL	_IO_PORT2_IO_RESV32_16
	.GLOBAL	_IO_PORT2_IO_RESV32_17
	.GLOBAL	_IO_PORT2_IO_RESV32_18
	.GLOBAL	_IO_PORT2_IO_RESV32_19
	.GLOBAL	_IO_PORT2_IO_RESV32_20
	.GLOBAL	_IO_PORT2_IO_RESV32_21
	.GLOBAL	_IO_PORT2_IO_RESV32_22
	.GLOBAL	_IO_PORT2_IO_RESV32_23
	.GLOBAL	_IO_PORT2_IO_RESV32_24
	.GLOBAL	_IO_PORT2_IO_RESV32_25
	.GLOBAL	_IO_PORT2_IO_RESV32_26
	.GLOBAL	_IO_PORT2_IO_RESV32_27
	.GLOBAL	_IO_PORT2_IO_RESV32_28
	.GLOBAL	_IO_PORT2_IO_RESV32_29
	.GLOBAL	_IO_PORT2_IO_RESV32_30
	.GLOBAL	_IO_PORT2_IO_RESV32_31
	.GLOBAL	_IO_PORT2_IO_RESV32_32
	.GLOBAL	_IO_PORT2_IO_RESV32_33
	.GLOBAL	_IO_PORT2_IO_RESV32_34
	.GLOBAL	_IO_PORT2_IO_RESV32_35
	.GLOBAL	_IO_PORT2_IO_RESV32_36
	.GLOBAL	_IO_PORT2_IO_RESV32_37
	.GLOBAL	_IO_PORT2_IO_RESV32_38
	.GLOBAL	_IO_PORT2_IO_RESV32_39
	.GLOBAL	_IO_PORT2_IO_RESV32_40
	.GLOBAL	_IO_PORT2_IO_RESV32_41
	.GLOBAL	_IO_PORT2_IO_RESV32_42
	.GLOBAL	_IO_PORT2_IO_RESV32_43
	.GLOBAL	_IO_PORT2_IO_RESV32_44
	.GLOBAL	_IO_PORT2_IO_RESV32_45
	.GLOBAL	_IO_PORT2_IO_DDR14
	.GLOBAL	_IO_PORT2_IO_DDR15
	.GLOBAL	_IO_PORT2_IO_DDR16
	.GLOBAL	_IO_PORT2_IO_DDR17
	.GLOBAL	_IO_PORT2_IO_DDR18
	.GLOBAL	_IO_PORT2_IO_DDR19
	.GLOBAL	_IO_PORT2_IO_RESV084
	.GLOBAL	_IO_PORT2_IO_RESV085
	.GLOBAL	_IO_PORT2_IO_DDR22
	.GLOBAL	_IO_PORT2_IO_DDR23
	.GLOBAL	_IO_PORT2_IO_DDR24
	.GLOBAL	_IO_PORT2_IO_RESV089
	.GLOBAL	_IO_PORT2_IO_RESV090
	.GLOBAL	_IO_PORT2_IO_DDR27
	.GLOBAL	_IO_PORT2_IO_DDR28
	.GLOBAL	_IO_PORT2_IO_DDR29
	.GLOBAL	_IO_PORT2_IO_RESV94
	.GLOBAL	_IO_PORT2_IO_DDR31
	.GLOBAL	_IO_PORT2_IO_RESV96
	.GLOBAL	_IO_PORT2_IO_RESV96_0
	.GLOBAL	_IO_PORT2_IO_RESV96_1
	.GLOBAL	_IO_PORT2_IO_RESV96_2
	.GLOBAL	_IO_PORT2_IO_RESV96_3
	.GLOBAL	_IO_PORT2_IO_RESV96_4
	.GLOBAL	_IO_PORT2_IO_RESV96_5
	.GLOBAL	_IO_PORT2_IO_RESV96_6
	.GLOBAL	_IO_PORT2_IO_RESV96_7
	.GLOBAL	_IO_PORT2_IO_RESV96_8
	.GLOBAL	_IO_PORT2_IO_RESV96_9
	.GLOBAL	_IO_PORT2_IO_RESV96_10
	.GLOBAL	_IO_PORT2_IO_RESV96_11
	.GLOBAL	_IO_PORT2_IO_RESV96_12
	.GLOBAL	_IO_PORT2_IO_RESV96_13
	.GLOBAL	_IO_PORT2_IO_RESV96_14
	.GLOBAL	_IO_PORT2_IO_RESV96_15
	.GLOBAL	_IO_PORT2_IO_RESV96_16
	.GLOBAL	_IO_PORT2_IO_RESV96_17
	.GLOBAL	_IO_PORT2_IO_RESV96_18
	.GLOBAL	_IO_PORT2_IO_RESV96_19
	.GLOBAL	_IO_PORT2_IO_RESV96_20
	.GLOBAL	_IO_PORT2_IO_RESV96_21
	.GLOBAL	_IO_PORT2_IO_RESV96_22
	.GLOBAL	_IO_PORT2_IO_RESV96_23
	.GLOBAL	_IO_PORT2_IO_RESV96_24
	.GLOBAL	_IO_PORT2_IO_RESV96_25
	.GLOBAL	_IO_PORT2_IO_RESV96_26
	.GLOBAL	_IO_PORT2_IO_RESV96_27
	.GLOBAL	_IO_PORT2_IO_RESV96_28
	.GLOBAL	_IO_PORT2_IO_RESV96_29
	.GLOBAL	_IO_PORT2_IO_RESV96_30
	.GLOBAL	_IO_PORT2_IO_RESV96_31
	.GLOBAL	_IO_PORT2_IO_RESV96_32
	.GLOBAL	_IO_PORT2_IO_RESV96_33
	.GLOBAL	_IO_PORT2_IO_RESV96_34
	.GLOBAL	_IO_PORT2_IO_RESV96_35
	.GLOBAL	_IO_PORT2_IO_RESV96_36
	.GLOBAL	_IO_PORT2_IO_RESV96_37
	.GLOBAL	_IO_PORT2_IO_RESV96_38
	.GLOBAL	_IO_PORT2_IO_RESV96_39
	.GLOBAL	_IO_PORT2_IO_RESV96_40
	.GLOBAL	_IO_PORT2_IO_RESV96_41
	.GLOBAL	_IO_PORT2_IO_RESV96_42
	.GLOBAL	_IO_PORT2_IO_RESV96_43
	.GLOBAL	_IO_PORT2_IO_RESV96_44
	.GLOBAL	_IO_PORT2_IO_RESV96_45
	.GLOBAL	_IO_PORT2_IO_PFR14
	.GLOBAL	_IO_PORT2_IO_PFR15
	.GLOBAL	_IO_PORT2_IO_PFR16
	.GLOBAL	_IO_PORT2_IO_PFR17
	.GLOBAL	_IO_PORT2_IO_PFR18
	.GLOBAL	_IO_PORT2_IO_PFR19
	.GLOBAL	_IO_PORT2_IO_RESV148
	.GLOBAL	_IO_PORT2_IO_RESV149
	.GLOBAL	_IO_PORT2_IO_PFR22
	.GLOBAL	_IO_PORT2_IO_PFR23
	.GLOBAL	_IO_PORT2_IO_PFR24
	.GLOBAL	_IO_PORT2_IO_RESV153
	.GLOBAL	_IO_PORT2_IO_RESV154
	.GLOBAL	_IO_PORT2_IO_PFR27
	.GLOBAL	_IO_PORT2_IO_PFR28
	.GLOBAL	_IO_PORT2_IO_PFR29
	.GLOBAL	_IO_PORT2_IO_RESV158
	.GLOBAL	_IO_PORT2_IO_PFR31
	.GLOBAL	_IO_PORT2_IO_RESV160
	.GLOBAL	_IO_PORT2_IO_RESV160_0
	.GLOBAL	_IO_PORT2_IO_RESV160_1
	.GLOBAL	_IO_PORT2_IO_RESV160_2
	.GLOBAL	_IO_PORT2_IO_RESV160_3
	.GLOBAL	_IO_PORT2_IO_RESV160_4
	.GLOBAL	_IO_PORT2_IO_RESV160_5
	.GLOBAL	_IO_PORT2_IO_RESV160_6
	.GLOBAL	_IO_PORT2_IO_RESV160_7
	.GLOBAL	_IO_PORT2_IO_RESV160_8
	.GLOBAL	_IO_PORT2_IO_RESV160_9
	.GLOBAL	_IO_PORT2_IO_RESV160_10
	.GLOBAL	_IO_PORT2_IO_RESV160_11
	.GLOBAL	_IO_PORT2_IO_RESV160_12
	.GLOBAL	_IO_PORT2_IO_RESV160_13
	.GLOBAL	_IO_PORT2_IO_RESV160_14
	.GLOBAL	_IO_PORT2_IO_RESV160_15
	.GLOBAL	_IO_PORT2_IO_RESV160_16
	.GLOBAL	_IO_PORT2_IO_RESV160_17
	.GLOBAL	_IO_PORT2_IO_RESV160_18
	.GLOBAL	_IO_PORT2_IO_RESV160_19
	.GLOBAL	_IO_PORT2_IO_RESV160_20
	.GLOBAL	_IO_PORT2_IO_RESV160_21
	.GLOBAL	_IO_PORT2_IO_RESV160_22
	.GLOBAL	_IO_PORT2_IO_RESV160_23
	.GLOBAL	_IO_PORT2_IO_RESV160_24
	.GLOBAL	_IO_PORT2_IO_RESV160_25
	.GLOBAL	_IO_PORT2_IO_RESV160_26
	.GLOBAL	_IO_PORT2_IO_RESV160_27
	.GLOBAL	_IO_PORT2_IO_RESV160_28
	.GLOBAL	_IO_PORT2_IO_RESV160_29
	.GLOBAL	_IO_PORT2_IO_RESV160_30
	.GLOBAL	_IO_PORT2_IO_RESV160_31
	.GLOBAL	_IO_PORT2_IO_RESV160_32
	.GLOBAL	_IO_PORT2_IO_RESV160_33
	.GLOBAL	_IO_PORT2_IO_RESV160_34
	.GLOBAL	_IO_PORT2_IO_RESV160_35
	.GLOBAL	_IO_PORT2_IO_RESV160_36
	.GLOBAL	_IO_PORT2_IO_RESV160_37
	.GLOBAL	_IO_PORT2_IO_RESV160_38
	.GLOBAL	_IO_PORT2_IO_RESV160_39
	.GLOBAL	_IO_PORT2_IO_RESV160_40
	.GLOBAL	_IO_PORT2_IO_RESV160_41
	.GLOBAL	_IO_PORT2_IO_RESV160_42
	.GLOBAL	_IO_PORT2_IO_RESV160_43
	.GLOBAL	_IO_PORT2_IO_RESV160_44
	.GLOBAL	_IO_PORT2_IO_RESV160_45
	.GLOBAL	_IO_PORT2_IO_EPFR14
	.GLOBAL	_IO_PORT2_IO_EPFR15
	.GLOBAL	_IO_PORT2_IO_EPFR16
	.GLOBAL	_IO_PORT2_IO_EPFR17
	.GLOBAL	_IO_PORT2_IO_EPFR18
	.GLOBAL	_IO_PORT2_IO_EPFR19
	.GLOBAL	_IO_PORT2_IO_RESV212
	.GLOBAL	_IO_PORT2_IO_RESV213
	.GLOBAL	_IO_PORT2_IO_EPFR22
	.GLOBAL	_IO_PORT2_IO_EPFR23
	.GLOBAL	_IO_PORT2_IO_EPFR24
	.GLOBAL	_IO_PORT2_IO_RESV217
	.GLOBAL	_IO_PORT2_IO_RESV218
	.GLOBAL	_IO_PORT2_IO_EPFR27
	.GLOBAL	_IO_PORT2_IO_EPFR28
	.GLOBAL	_IO_PORT2_IO_EPFR29
	.GLOBAL	_IO_PORT2_IO_RESV222
	.GLOBAL	_IO_PORT2_IO_EPFR31
	.GLOBAL	_IO_PORT2_IO_RESV224
	.GLOBAL	_IO_PORT2_IO_RESV224_0
	.GLOBAL	_IO_PORT2_IO_RESV224_1
	.GLOBAL	_IO_PORT2_IO_RESV224_2
	.GLOBAL	_IO_PORT2_IO_RESV224_3
	.GLOBAL	_IO_PORT2_IO_RESV224_4
	.GLOBAL	_IO_PORT2_IO_RESV224_5
	.GLOBAL	_IO_PORT2_IO_RESV224_6
	.GLOBAL	_IO_PORT2_IO_RESV224_7
	.GLOBAL	_IO_PORT2_IO_RESV224_8
	.GLOBAL	_IO_PORT2_IO_RESV224_9
	.GLOBAL	_IO_PORT2_IO_RESV224_10
	.GLOBAL	_IO_PORT2_IO_RESV224_11
	.GLOBAL	_IO_PORT2_IO_RESV224_12
	.GLOBAL	_IO_PORT2_IO_RESV224_13
	.GLOBAL	_IO_PORT2_IO_RESV224_14
	.GLOBAL	_IO_PORT2_IO_RESV224_15
	.GLOBAL	_IO_PORT2_IO_RESV224_16
	.GLOBAL	_IO_PORT2_IO_RESV224_17
	.GLOBAL	_IO_PORT2_IO_RESV224_18
	.GLOBAL	_IO_PORT2_IO_RESV224_19
	.GLOBAL	_IO_PORT2_IO_RESV224_20
	.GLOBAL	_IO_PORT2_IO_RESV224_21
	.GLOBAL	_IO_PORT2_IO_RESV224_22
	.GLOBAL	_IO_PORT2_IO_RESV224_23
	.GLOBAL	_IO_PORT2_IO_RESV224_24
	.GLOBAL	_IO_PORT2_IO_RESV224_25
	.GLOBAL	_IO_PORT2_IO_RESV224_26
	.GLOBAL	_IO_PORT2_IO_RESV224_27
	.GLOBAL	_IO_PORT2_IO_RESV224_28
	.GLOBAL	_IO_PORT2_IO_RESV224_29
	.GLOBAL	_IO_PORT2_IO_RESV224_30
	.GLOBAL	_IO_PORT2_IO_RESV224_31
	.GLOBAL	_IO_PORT2_IO_RESV224_32
	.GLOBAL	_IO_PORT2_IO_RESV224_33
	.GLOBAL	_IO_PORT2_IO_RESV224_34
	.GLOBAL	_IO_PORT2_IO_RESV224_35
	.GLOBAL	_IO_PORT2_IO_RESV224_36
	.GLOBAL	_IO_PORT2_IO_RESV224_37
	.GLOBAL	_IO_PORT2_IO_RESV224_38
	.GLOBAL	_IO_PORT2_IO_RESV224_39
	.GLOBAL	_IO_PORT2_IO_RESV224_40
	.GLOBAL	_IO_PORT2_IO_RESV224_41
	.GLOBAL	_IO_PORT2_IO_RESV224_42
	.GLOBAL	_IO_PORT2_IO_RESV224_43
	.GLOBAL	_IO_PORT2_IO_RESV224_44
	.GLOBAL	_IO_PORT2_IO_RESV224_45
	.GLOBAL	_IO_PORT2_IO_PODR14
	.GLOBAL	_IO_PORT2_IO_PODR15
	.GLOBAL	_IO_PORT2_IO_PODR16
	.GLOBAL	_IO_PORT2_IO_PODR17
	.GLOBAL	_IO_PORT2_IO_PODR18
	.GLOBAL	_IO_PORT2_IO_PODR19
	.GLOBAL	_IO_PORT2_IO_RESV276
	.GLOBAL	_IO_PORT2_IO_RESV277
	.GLOBAL	_IO_PORT2_IO_PODR22
	.GLOBAL	_IO_PORT2_IO_PODR23
	.GLOBAL	_IO_PORT2_IO_PODR24
	.GLOBAL	_IO_PORT2_IO_RESV281
	.GLOBAL	_IO_PORT2_IO_RESV282
	.GLOBAL	_IO_PORT2_IO_PODR27
	.GLOBAL	_IO_PORT2_IO_PODR28
	.GLOBAL	_IO_PORT2_IO_PODR29
	.GLOBAL	_IO_PORT2_IO_RESV286
	.GLOBAL	_IO_PORT2_IO_PODR31
	.GLOBAL	_IO_PORT2_IO_RESV288
	.GLOBAL	_IO_PORT2_IO_RESV288_0
	.GLOBAL	_IO_PORT2_IO_RESV288_1
	.GLOBAL	_IO_PORT2_IO_RESV288_2
	.GLOBAL	_IO_PORT2_IO_RESV288_3
	.GLOBAL	_IO_PORT2_IO_RESV288_4
	.GLOBAL	_IO_PORT2_IO_RESV288_5
	.GLOBAL	_IO_PORT2_IO_RESV288_6
	.GLOBAL	_IO_PORT2_IO_RESV288_7
	.GLOBAL	_IO_PORT2_IO_RESV288_8
	.GLOBAL	_IO_PORT2_IO_RESV288_9
	.GLOBAL	_IO_PORT2_IO_RESV288_10
	.GLOBAL	_IO_PORT2_IO_RESV288_11
	.GLOBAL	_IO_PORT2_IO_RESV288_12
	.GLOBAL	_IO_PORT2_IO_RESV288_13
	.GLOBAL	_IO_PORT2_IO_RESV288_14
	.GLOBAL	_IO_PORT2_IO_RESV288_15
	.GLOBAL	_IO_PORT2_IO_RESV288_16
	.GLOBAL	_IO_PORT2_IO_RESV288_17
	.GLOBAL	_IO_PORT2_IO_RESV288_18
	.GLOBAL	_IO_PORT2_IO_RESV288_19
	.GLOBAL	_IO_PORT2_IO_RESV288_20
	.GLOBAL	_IO_PORT2_IO_RESV288_21
	.GLOBAL	_IO_PORT2_IO_RESV288_22
	.GLOBAL	_IO_PORT2_IO_RESV288_23
	.GLOBAL	_IO_PORT2_IO_RESV288_24
	.GLOBAL	_IO_PORT2_IO_RESV288_25
	.GLOBAL	_IO_PORT2_IO_RESV288_26
	.GLOBAL	_IO_PORT2_IO_RESV288_27
	.GLOBAL	_IO_PORT2_IO_RESV288_28
	.GLOBAL	_IO_PORT2_IO_RESV288_29
	.GLOBAL	_IO_PORT2_IO_RESV288_30
	.GLOBAL	_IO_PORT2_IO_RESV288_31
	.GLOBAL	_IO_PORT2_IO_RESV288_32
	.GLOBAL	_IO_PORT2_IO_RESV288_33
	.GLOBAL	_IO_PORT2_IO_RESV288_34
	.GLOBAL	_IO_PORT2_IO_RESV288_35
	.GLOBAL	_IO_PORT2_IO_RESV288_36
	.GLOBAL	_IO_PORT2_IO_RESV288_37
	.GLOBAL	_IO_PORT2_IO_RESV288_38
	.GLOBAL	_IO_PORT2_IO_RESV288_39
	.GLOBAL	_IO_PORT2_IO_RESV288_40
	.GLOBAL	_IO_PORT2_IO_RESV288_41
	.GLOBAL	_IO_PORT2_IO_RESV288_42
	.GLOBAL	_IO_PORT2_IO_RESV288_43
	.GLOBAL	_IO_PORT2_IO_RESV288_44
	.GLOBAL	_IO_PORT2_IO_RESV288_45
	.GLOBAL	_IO_PORT2_IO_PILR14
	.GLOBAL	_IO_PORT2_IO_PILR15
	.GLOBAL	_IO_PORT2_IO_PILR16
	.GLOBAL	_IO_PORT2_IO_PILR17
	.GLOBAL	_IO_PORT2_IO_PILR18
	.GLOBAL	_IO_PORT2_IO_PILR19
	.GLOBAL	_IO_PORT2_IO_RESV340
	.GLOBAL	_IO_PORT2_IO_RESV341
	.GLOBAL	_IO_PORT2_IO_PILR22
	.GLOBAL	_IO_PORT2_IO_PILR23
	.GLOBAL	_IO_PORT2_IO_PILR24
	.GLOBAL	_IO_PORT2_IO_RESV345
	.GLOBAL	_IO_PORT2_IO_RESV346
	.GLOBAL	_IO_PORT2_IO_PILR27
	.GLOBAL	_IO_PORT2_IO_PILR28
	.GLOBAL	_IO_PORT2_IO_PILR29
	.GLOBAL	_IO_PORT2_IO_RESV350
	.GLOBAL	_IO_PORT2_IO_PILR31
	.GLOBAL	_IO_PORT2_IO_RESV352
	.GLOBAL	_IO_PORT2_IO_RESV352_0
	.GLOBAL	_IO_PORT2_IO_RESV352_1
	.GLOBAL	_IO_PORT2_IO_RESV352_2
	.GLOBAL	_IO_PORT2_IO_RESV352_3
	.GLOBAL	_IO_PORT2_IO_RESV352_4
	.GLOBAL	_IO_PORT2_IO_RESV352_5
	.GLOBAL	_IO_PORT2_IO_RESV352_6
	.GLOBAL	_IO_PORT2_IO_RESV352_7
	.GLOBAL	_IO_PORT2_IO_RESV352_8
	.GLOBAL	_IO_PORT2_IO_RESV352_9
	.GLOBAL	_IO_PORT2_IO_RESV352_10
	.GLOBAL	_IO_PORT2_IO_RESV352_11
	.GLOBAL	_IO_PORT2_IO_RESV352_12
	.GLOBAL	_IO_PORT2_IO_RESV352_13
	.GLOBAL	_IO_PORT2_IO_RESV352_14
	.GLOBAL	_IO_PORT2_IO_RESV352_15
	.GLOBAL	_IO_PORT2_IO_RESV352_16
	.GLOBAL	_IO_PORT2_IO_RESV352_17
	.GLOBAL	_IO_PORT2_IO_RESV352_18
	.GLOBAL	_IO_PORT2_IO_RESV352_19
	.GLOBAL	_IO_PORT2_IO_RESV352_20
	.GLOBAL	_IO_PORT2_IO_RESV352_21
	.GLOBAL	_IO_PORT2_IO_RESV352_22
	.GLOBAL	_IO_PORT2_IO_RESV352_23
	.GLOBAL	_IO_PORT2_IO_RESV352_24
	.GLOBAL	_IO_PORT2_IO_RESV352_25
	.GLOBAL	_IO_PORT2_IO_RESV352_26
	.GLOBAL	_IO_PORT2_IO_RESV352_27
	.GLOBAL	_IO_PORT2_IO_RESV352_28
	.GLOBAL	_IO_PORT2_IO_RESV352_29
	.GLOBAL	_IO_PORT2_IO_RESV352_30
	.GLOBAL	_IO_PORT2_IO_RESV352_31
	.GLOBAL	_IO_PORT2_IO_RESV352_32
	.GLOBAL	_IO_PORT2_IO_RESV352_33
	.GLOBAL	_IO_PORT2_IO_RESV352_34
	.GLOBAL	_IO_PORT2_IO_RESV352_35
	.GLOBAL	_IO_PORT2_IO_RESV352_36
	.GLOBAL	_IO_PORT2_IO_RESV352_37
	.GLOBAL	_IO_PORT2_IO_RESV352_38
	.GLOBAL	_IO_PORT2_IO_RESV352_39
	.GLOBAL	_IO_PORT2_IO_RESV352_40
	.GLOBAL	_IO_PORT2_IO_RESV352_41
	.GLOBAL	_IO_PORT2_IO_RESV352_42
	.GLOBAL	_IO_PORT2_IO_RESV352_43
	.GLOBAL	_IO_PORT2_IO_RESV352_44
	.GLOBAL	_IO_PORT2_IO_RESV352_45
	.GLOBAL	_IO_PORT2_IO_EPILR14
	.GLOBAL	_IO_PORT2_IO_EPILR15
	.GLOBAL	_IO_PORT2_IO_EPILR16
	.GLOBAL	_IO_PORT2_IO_EPILR17
	.GLOBAL	_IO_PORT2_IO_EPILR18
	.GLOBAL	_IO_PORT2_IO_EPILR19
	.GLOBAL	_IO_PORT2_IO_RESV404
	.GLOBAL	_IO_PORT2_IO_RESV405
	.GLOBAL	_IO_PORT2_IO_EPILR22
	.GLOBAL	_IO_PORT2_IO_EPILR23
	.GLOBAL	_IO_PORT2_IO_EPILR24
	.GLOBAL	_IO_PORT2_IO_RESV409
	.GLOBAL	_IO_PORT2_IO_RESV410
	.GLOBAL	_IO_PORT2_IO_EPILR27
	.GLOBAL	_IO_PORT2_IO_EPILR28
	.GLOBAL	_IO_PORT2_IO_EPILR29
	.GLOBAL	_IO_PORT2_IO_RESV414
	.GLOBAL	_IO_PORT2_IO_EPILR31
	.GLOBAL	_IO_PORT2_IO_RESV416
	.GLOBAL	_IO_PORT2_IO_RESV416_0
	.GLOBAL	_IO_PORT2_IO_RESV416_1
	.GLOBAL	_IO_PORT2_IO_RESV416_2
	.GLOBAL	_IO_PORT2_IO_RESV416_3
	.GLOBAL	_IO_PORT2_IO_RESV416_4
	.GLOBAL	_IO_PORT2_IO_RESV416_5
	.GLOBAL	_IO_PORT2_IO_RESV416_6
	.GLOBAL	_IO_PORT2_IO_RESV416_7
	.GLOBAL	_IO_PORT2_IO_RESV416_8
	.GLOBAL	_IO_PORT2_IO_RESV416_9
	.GLOBAL	_IO_PORT2_IO_RESV416_10
	.GLOBAL	_IO_PORT2_IO_RESV416_11
	.GLOBAL	_IO_PORT2_IO_RESV416_12
	.GLOBAL	_IO_PORT2_IO_RESV416_13
	.GLOBAL	_IO_PORT2_IO_RESV416_14
	.GLOBAL	_IO_PORT2_IO_RESV416_15
	.GLOBAL	_IO_PORT2_IO_RESV416_16
	.GLOBAL	_IO_PORT2_IO_RESV416_17
	.GLOBAL	_IO_PORT2_IO_RESV416_18
	.GLOBAL	_IO_PORT2_IO_RESV416_19
	.GLOBAL	_IO_PORT2_IO_RESV416_20
	.GLOBAL	_IO_PORT2_IO_RESV416_21
	.GLOBAL	_IO_PORT2_IO_RESV416_22
	.GLOBAL	_IO_PORT2_IO_RESV416_23
	.GLOBAL	_IO_PORT2_IO_RESV416_24
	.GLOBAL	_IO_PORT2_IO_RESV416_25
	.GLOBAL	_IO_PORT2_IO_RESV416_26
	.GLOBAL	_IO_PORT2_IO_RESV416_27
	.GLOBAL	_IO_PORT2_IO_RESV416_28
	.GLOBAL	_IO_PORT2_IO_RESV416_29
	.GLOBAL	_IO_PORT2_IO_RESV416_30
	.GLOBAL	_IO_PORT2_IO_RESV416_31
	.GLOBAL	_IO_PORT2_IO_RESV416_32
	.GLOBAL	_IO_PORT2_IO_RESV416_33
	.GLOBAL	_IO_PORT2_IO_RESV416_34
	.GLOBAL	_IO_PORT2_IO_RESV416_35
	.GLOBAL	_IO_PORT2_IO_RESV416_36
	.GLOBAL	_IO_PORT2_IO_RESV416_37
	.GLOBAL	_IO_PORT2_IO_RESV416_38
	.GLOBAL	_IO_PORT2_IO_RESV416_39
	.GLOBAL	_IO_PORT2_IO_RESV416_40
	.GLOBAL	_IO_PORT2_IO_RESV416_41
	.GLOBAL	_IO_PORT2_IO_RESV416_42
	.GLOBAL	_IO_PORT2_IO_RESV416_43
	.GLOBAL	_IO_PORT2_IO_RESV416_44
	.GLOBAL	_IO_PORT2_IO_RESV416_45
	.GLOBAL	_IO_PORT2_IO_PPER14
	.GLOBAL	_IO_PORT2_IO_PPER15
	.GLOBAL	_IO_PORT2_IO_PPER16
	.GLOBAL	_IO_PORT2_IO_PPER17
	.GLOBAL	_IO_PORT2_IO_PPER18
	.GLOBAL	_IO_PORT2_IO_PPER19
	.GLOBAL	_IO_PORT2_IO_RESV468
	.GLOBAL	_IO_PORT2_IO_RESV469
	.GLOBAL	_IO_PORT2_IO_PPER22
	.GLOBAL	_IO_PORT2_IO_PPER23
	.GLOBAL	_IO_PORT2_IO_PPER24
	.GLOBAL	_IO_PORT2_IO_RESV473
	.GLOBAL	_IO_PORT2_IO_RESV474
	.GLOBAL	_IO_PORT2_IO_PPER27
	.GLOBAL	_IO_PORT2_IO_PPER28
	.GLOBAL	_IO_PORT2_IO_PPER29
	.GLOBAL	_IO_PORT2_IO_RESV478
	.GLOBAL	_IO_PORT2_IO_PPER31
	.GLOBAL	_IO_PORT2_IO_RESV480
	.GLOBAL	_IO_PORT2_IO_RESV480_0
	.GLOBAL	_IO_PORT2_IO_RESV480_1
	.GLOBAL	_IO_PORT2_IO_RESV480_2
	.GLOBAL	_IO_PORT2_IO_RESV480_3
	.GLOBAL	_IO_PORT2_IO_RESV480_4
	.GLOBAL	_IO_PORT2_IO_RESV480_5
	.GLOBAL	_IO_PORT2_IO_RESV480_6
	.GLOBAL	_IO_PORT2_IO_RESV480_7
	.GLOBAL	_IO_PORT2_IO_RESV480_8
	.GLOBAL	_IO_PORT2_IO_RESV480_9
	.GLOBAL	_IO_PORT2_IO_RESV480_10
	.GLOBAL	_IO_PORT2_IO_RESV480_11
	.GLOBAL	_IO_PORT2_IO_RESV480_12
	.GLOBAL	_IO_PORT2_IO_RESV480_13
	.GLOBAL	_IO_PORT2_IO_RESV480_14
	.GLOBAL	_IO_PORT2_IO_RESV480_15
	.GLOBAL	_IO_PORT2_IO_RESV480_16
	.GLOBAL	_IO_PORT2_IO_RESV480_17
	.GLOBAL	_IO_PORT2_IO_RESV480_18
	.GLOBAL	_IO_PORT2_IO_RESV480_19
	.GLOBAL	_IO_PORT2_IO_RESV480_20
	.GLOBAL	_IO_PORT2_IO_RESV480_21
	.GLOBAL	_IO_PORT2_IO_RESV480_22
	.GLOBAL	_IO_PORT2_IO_RESV480_23
	.GLOBAL	_IO_PORT2_IO_RESV480_24
	.GLOBAL	_IO_PORT2_IO_RESV480_25
	.GLOBAL	_IO_PORT2_IO_RESV480_26
	.GLOBAL	_IO_PORT2_IO_RESV480_27
	.GLOBAL	_IO_PORT2_IO_RESV480_28
	.GLOBAL	_IO_PORT2_IO_RESV480_29
	.GLOBAL	_IO_PORT2_IO_RESV480_30
	.GLOBAL	_IO_PORT2_IO_RESV480_31
	.GLOBAL	_IO_PORT2_IO_RESV480_32
	.GLOBAL	_IO_PORT2_IO_RESV480_33
	.GLOBAL	_IO_PORT2_IO_RESV480_34
	.GLOBAL	_IO_PORT2_IO_RESV480_35
	.GLOBAL	_IO_PORT2_IO_RESV480_36
	.GLOBAL	_IO_PORT2_IO_RESV480_37
	.GLOBAL	_IO_PORT2_IO_RESV480_38
	.GLOBAL	_IO_PORT2_IO_RESV480_39
	.GLOBAL	_IO_PORT2_IO_RESV480_40
	.GLOBAL	_IO_PORT2_IO_RESV480_41
	.GLOBAL	_IO_PORT2_IO_RESV480_42
	.GLOBAL	_IO_PORT2_IO_RESV480_43
	.GLOBAL	_IO_PORT2_IO_RESV480_44
	.GLOBAL	_IO_PORT2_IO_RESV480_45
	.GLOBAL	_IO_PORT2_IO_PPCR14
	.GLOBAL	_IO_PORT2_IO_PPCR15
	.GLOBAL	_IO_PORT2_IO_PPCR16
	.GLOBAL	_IO_PORT2_IO_PPCR17
	.GLOBAL	_IO_PORT2_IO_PPCR18
	.GLOBAL	_IO_PORT2_IO_PPCR19
	.GLOBAL	_IO_PORT2_IO_RESV532
	.GLOBAL	_IO_PORT2_IO_RESV533
	.GLOBAL	_IO_PORT2_IO_PPCR22
	.GLOBAL	_IO_PORT2_IO_PPCR23
	.GLOBAL	_IO_PORT2_IO_PPCR24
	.GLOBAL	_IO_PORT2_IO_RESV537
	.GLOBAL	_IO_PORT2_IO_RESV538
	.GLOBAL	_IO_PORT2_IO_PPCR27
	.GLOBAL	_IO_PORT2_IO_PPCR28
	.GLOBAL	_IO_PORT2_IO_PPCR29
	.GLOBAL	_IO_PORT2_IO_RESV542
	.GLOBAL	_IO_PORT2_IO_PPCR31

#ifdef __IO_DEFINE
	.SECTION	IO_DMAD,DATA,locate=0x1000
_IO_DMAD:	.res.b	0
_IO_DMAD_IO_DMASA0:	.res.b	4
_IO_DMAD_IO_DMADA0:	.res.b	4
_IO_DMAD_IO_DMASA1:	.res.b	4
_IO_DMAD_IO_DMADA1:	.res.b	4
_IO_DMAD_IO_DMASA2:	.res.b	4
_IO_DMAD_IO_DMADA2:	.res.b	4
_IO_DMAD_IO_DMASA3:	.res.b	4
_IO_DMAD_IO_DMADA3:	.res.b	4
_IO_DMAD_IO_DMASA4:	.res.b	4
_IO_DMAD_IO_DMADA4:	.res.b	4
#endif
	.GLOBAL	_IO_DMAD
	.GLOBAL	_IO_DMAD_IO_DMASA0
	.GLOBAL	_IO_DMAD_IO_DMADA0
	.GLOBAL	_IO_DMAD_IO_DMASA1
	.GLOBAL	_IO_DMAD_IO_DMADA1
	.GLOBAL	_IO_DMAD_IO_DMASA2
	.GLOBAL	_IO_DMAD_IO_DMADA2
	.GLOBAL	_IO_DMAD_IO_DMASA3
	.GLOBAL	_IO_DMAD_IO_DMADA3
	.GLOBAL	_IO_DMAD_IO_DMASA4
	.GLOBAL	_IO_DMAD_IO_DMADA4

#ifdef __IO_DEFINE
	.SECTION	IO_FMCS,DATA,locate=0x7000
_IO_FMCS:
__fmcs:	.res.b	1
FMCS	.equ	0x7000
#endif
	.GLOBAL	_IO_FMCS, __fmcs, FMCS

#ifdef __IO_DEFINE
	.SECTION	IO_FMCR,DATA,locate=0x7001
_IO_FMCR:
__fmcr:	.res.b	1
FMCR	.equ	0x7001
#endif
	.GLOBAL	_IO_FMCR, __fmcr, FMCR

#ifdef __IO_DEFINE
	.SECTION	IO_FCHCR,DATA,locate=0x7002
_IO_FCHCR:
__fchcr:	.res.b	2
FCHCR	.equ	0x7002
#endif
	.GLOBAL	_IO_FCHCR, __fchcr, FCHCR

#ifdef __IO_DEFINE
	.SECTION	IO_FMWT,DATA,locate=0x7004
_IO_FMWT:
__fmwt:	.res.b	2
FMWT	.equ	0x7004
#endif
	.GLOBAL	_IO_FMWT, __fmwt, FMWT

#ifdef __IO_DEFINE
	.SECTION	IO_FMWT2,DATA,locate=0x7006
_IO_FMWT2:
__fmwt2:	.res.b	1
FMWT2	.equ	0x7006
#endif
	.GLOBAL	_IO_FMWT2, __fmwt2, FMWT2

#ifdef __IO_DEFINE
	.SECTION	IO_FMPS,DATA,locate=0x7007
_IO_FMPS:
__fmps:	.res.b	1
FMPS	.equ	0x7007
#endif
	.GLOBAL	_IO_FMPS, __fmps, FMPS

#ifdef __IO_DEFINE
	.SECTION	IO_FMAC,DATA,locate=0x7008
_IO_FMAC:
__FMAC:	.res.b	4
FMAC	.equ	0x7008
#endif
	.GLOBAL	_IO_FMAC, __FMAC, FMAC

#ifdef __IO_DEFINE
	.SECTION	IO_CAN0,DATA,locate=0xC000
_IO_CAN0:	.res.b	0
_IO_CAN0_IO_CTRLR0:	.res.b	2
_IO_CAN0_IO_STATR0:	.res.b	2
_IO_CAN0_IO_ERRCNT0:	.res.b	2
_IO_CAN0_IO_BTR0:	.res.b	2
_IO_CAN0_IO_INTR0:	.res.b	2
_IO_CAN0_IO_TESTR0:	.res.b	2
_IO_CAN0_IO_BRPER0:	.res.b	2
_IO_CAN0_IO_RESV1:	.res.b	2
_IO_CAN0_IO_IF1CREQ0:	.res.b	2
_IO_CAN0_IO_IF1CMSK0:	.res.b	2
_IO_CAN0_IO_IF1MSK0:	.res.b	4
_IO_CAN0_IO_IF1ARB0:	.res.b	4
_IO_CAN0_IO_IF1MCTR0:	.res.b	2
_IO_CAN0_IO_RESV2:	.res.b	2
_IO_CAN0_IO_IF1DTA10:	.res.b	2
_IO_CAN0_IO_IF1DTA20:	.res.b	2
_IO_CAN0_IO_IF1DTB10:	.res.b	2
_IO_CAN0_IO_IF1DTB20:	.res.b	2
_IO_CAN0_IO_RESV3	.res.b	24
_IO_CAN0_IO_IF2CREQ0:	.res.b	2
_IO_CAN0_IO_IF2CMSK0:	.res.b	2
_IO_CAN0_IO_IF2MSK0:	.res.b	4
_IO_CAN0_IO_IF2ARB0:	.res.b	4
_IO_CAN0_IO_IF2MCTR0:	.res.b	2
_IO_CAN0_IO_RESV4:	.res.b	2
_IO_CAN0_IO_IF2DTA10:	.res.b	2
_IO_CAN0_IO_IF2DTA20:	.res.b	2
_IO_CAN0_IO_IF2DTB10:	.res.b	2
_IO_CAN0_IO_IF2DTB20:	.res.b	2
_IO_CAN0_IO_RESV5	.res.b	40
_IO_CAN0_IO_TREQR0_12:	.res.b	4
_IO_CAN0_IO_RESV6:	.res.b	4
_IO_CAN0_IO_RESV7:	.res.b	4
_IO_CAN0_IO_RESV8:	.res.b	4
_IO_CAN0_IO_NEWDT0_12:	.res.b	4
_IO_CAN0_IO_RESV9:	.res.b	4
_IO_CAN0_IO_RESV10:	.res.b	4
_IO_CAN0_IO_RESV11:	.res.b	4
_IO_CAN0_IO_INTPND0_12:	.res.b	4
_IO_CAN0_IO_RESV12:	.res.b	4
_IO_CAN0_IO_RESV13:	.res.b	4
_IO_CAN0_IO_RESV14:	.res.b	4
_IO_CAN0_IO_MSGVAL0_12:	.res.b	4
_IO_CAN0_IO_RESV15:	.res.b	4
_IO_CAN0_IO_RESV16:	.res.b	4
_IO_CAN0_IO_RESV17:	.res.b	4
#endif
	.GLOBAL	_IO_CAN0
	.GLOBAL	_IO_CAN0_IO_CTRLR0
	.GLOBAL	_IO_CAN0_IO_STATR0
	.GLOBAL	_IO_CAN0_IO_ERRCNT0
	.GLOBAL	_IO_CAN0_IO_BTR0
	.GLOBAL	_IO_CAN0_IO_INTR0
	.GLOBAL	_IO_CAN0_IO_TESTR0
	.GLOBAL	_IO_CAN0_IO_BRPER0
	.GLOBAL	_IO_CAN0_IO_RESV1
	.GLOBAL	_IO_CAN0_IO_IF1CREQ0
	.GLOBAL	_IO_CAN0_IO_IF1CMSK0
	.GLOBAL	_IO_CAN0_IO_IF1MSK0
	.GLOBAL	_IO_CAN0_IO_IF1ARB0
	.GLOBAL	_IO_CAN0_IO_IF1MCTR0
	.GLOBAL	_IO_CAN0_IO_RESV2
	.GLOBAL	_IO_CAN0_IO_IF1DTA10
	.GLOBAL	_IO_CAN0_IO_IF1DTA20
	.GLOBAL	_IO_CAN0_IO_IF1DTB10
	.GLOBAL	_IO_CAN0_IO_IF1DTB20
	.GLOBAL	_IO_CAN0_IO_RESV3
	.GLOBAL	_IO_CAN0_IO_RESV3_0
	.GLOBAL	_IO_CAN0_IO_RESV3_1
	.GLOBAL	_IO_CAN0_IO_RESV3_2
	.GLOBAL	_IO_CAN0_IO_RESV3_3
	.GLOBAL	_IO_CAN0_IO_RESV3_4
	.GLOBAL	_IO_CAN0_IO_RESV3_5
	.GLOBAL	_IO_CAN0_IO_RESV3_6
	.GLOBAL	_IO_CAN0_IO_RESV3_7
	.GLOBAL	_IO_CAN0_IO_RESV3_8
	.GLOBAL	_IO_CAN0_IO_RESV3_9
	.GLOBAL	_IO_CAN0_IO_RESV3_10
	.GLOBAL	_IO_CAN0_IO_RESV3_11
	.GLOBAL	_IO_CAN0_IO_RESV3_12
	.GLOBAL	_IO_CAN0_IO_RESV3_13
	.GLOBAL	_IO_CAN0_IO_RESV3_14
	.GLOBAL	_IO_CAN0_IO_RESV3_15
	.GLOBAL	_IO_CAN0_IO_RESV3_16
	.GLOBAL	_IO_CAN0_IO_RESV3_17
	.GLOBAL	_IO_CAN0_IO_RESV3_18
	.GLOBAL	_IO_CAN0_IO_RESV3_19
	.GLOBAL	_IO_CAN0_IO_RESV3_20
	.GLOBAL	_IO_CAN0_IO_RESV3_21
	.GLOBAL	_IO_CAN0_IO_RESV3_22
	.GLOBAL	_IO_CAN0_IO_RESV3_23
	.GLOBAL	_IO_CAN0_IO_IF2CREQ0
	.GLOBAL	_IO_CAN0_IO_IF2CMSK0
	.GLOBAL	_IO_CAN0_IO_IF2MSK0
	.GLOBAL	_IO_CAN0_IO_IF2ARB0
	.GLOBAL	_IO_CAN0_IO_IF2MCTR0
	.GLOBAL	_IO_CAN0_IO_RESV4
	.GLOBAL	_IO_CAN0_IO_IF2DTA10
	.GLOBAL	_IO_CAN0_IO_IF2DTA20
	.GLOBAL	_IO_CAN0_IO_IF2DTB10
	.GLOBAL	_IO_CAN0_IO_IF2DTB20
	.GLOBAL	_IO_CAN0_IO_RESV5
	.GLOBAL	_IO_CAN0_IO_RESV5_0
	.GLOBAL	_IO_CAN0_IO_RESV5_1
	.GLOBAL	_IO_CAN0_IO_RESV5_2
	.GLOBAL	_IO_CAN0_IO_RESV5_3
	.GLOBAL	_IO_CAN0_IO_RESV5_4
	.GLOBAL	_IO_CAN0_IO_RESV5_5
	.GLOBAL	_IO_CAN0_IO_RESV5_6
	.GLOBAL	_IO_CAN0_IO_RESV5_7
	.GLOBAL	_IO_CAN0_IO_RESV5_8
	.GLOBAL	_IO_CAN0_IO_RESV5_9
	.GLOBAL	_IO_CAN0_IO_RESV5_10
	.GLOBAL	_IO_CAN0_IO_RESV5_11
	.GLOBAL	_IO_CAN0_IO_RESV5_12
	.GLOBAL	_IO_CAN0_IO_RESV5_13
	.GLOBAL	_IO_CAN0_IO_RESV5_14
	.GLOBAL	_IO_CAN0_IO_RESV5_15
	.GLOBAL	_IO_CAN0_IO_RESV5_16
	.GLOBAL	_IO_CAN0_IO_RESV5_17
	.GLOBAL	_IO_CAN0_IO_RESV5_18
	.GLOBAL	_IO_CAN0_IO_RESV5_19
	.GLOBAL	_IO_CAN0_IO_RESV5_20
	.GLOBAL	_IO_CAN0_IO_RESV5_21
	.GLOBAL	_IO_CAN0_IO_RESV5_22
	.GLOBAL	_IO_CAN0_IO_RESV5_23
	.GLOBAL	_IO_CAN0_IO_RESV5_24
	.GLOBAL	_IO_CAN0_IO_RESV5_25
	.GLOBAL	_IO_CAN0_IO_RESV5_26
	.GLOBAL	_IO_CAN0_IO_RESV5_27
	.GLOBAL	_IO_CAN0_IO_RESV5_28
	.GLOBAL	_IO_CAN0_IO_RESV5_29
	.GLOBAL	_IO_CAN0_IO_RESV5_30
	.GLOBAL	_IO_CAN0_IO_RESV5_31
	.GLOBAL	_IO_CAN0_IO_RESV5_32
	.GLOBAL	_IO_CAN0_IO_RESV5_33
	.GLOBAL	_IO_CAN0_IO_RESV5_34
	.GLOBAL	_IO_CAN0_IO_RESV5_35
	.GLOBAL	_IO_CAN0_IO_RESV5_36
	.GLOBAL	_IO_CAN0_IO_RESV5_37
	.GLOBAL	_IO_CAN0_IO_RESV5_38
	.GLOBAL	_IO_CAN0_IO_RESV5_39
	.GLOBAL	_IO_CAN0_IO_TREQR0_12
	.GLOBAL	_IO_CAN0_IO_RESV6
	.GLOBAL	_IO_CAN0_IO_RESV7
	.GLOBAL	_IO_CAN0_IO_RESV8
	.GLOBAL	_IO_CAN0_IO_NEWDT0_12
	.GLOBAL	_IO_CAN0_IO_RESV9
	.GLOBAL	_IO_CAN0_IO_RESV10
	.GLOBAL	_IO_CAN0_IO_RESV11
	.GLOBAL	_IO_CAN0_IO_INTPND0_12
	.GLOBAL	_IO_CAN0_IO_RESV12
	.GLOBAL	_IO_CAN0_IO_RESV13
	.GLOBAL	_IO_CAN0_IO_RESV14
	.GLOBAL	_IO_CAN0_IO_MSGVAL0_12
	.GLOBAL	_IO_CAN0_IO_RESV15
	.GLOBAL	_IO_CAN0_IO_RESV16
	.GLOBAL	_IO_CAN0_IO_RESV17

#ifdef __IO_DEFINE
	.SECTION	IO_CAN4,DATA,locate=0xC400
_IO_CAN4:	.res.b	0
_IO_CAN4_IO_CTRLR4:	.res.b	2
_IO_CAN4_IO_STATR4:	.res.b	2
_IO_CAN4_IO_ERRCNT4:	.res.b	2
_IO_CAN4_IO_BTR4:	.res.b	2
_IO_CAN4_IO_INTR4:	.res.b	2
_IO_CAN4_IO_TESTR4:	.res.b	2
_IO_CAN4_IO_BRPER4:	.res.b	2
_IO_CAN4_IO_RESV1:	.res.b	2
_IO_CAN4_IO_IF1CREQ4:	.res.b	2
_IO_CAN4_IO_IF1CMSK4:	.res.b	2
_IO_CAN4_IO_IF1MSK4:	.res.b	4
_IO_CAN4_IO_IF1ARB4:	.res.b	4
_IO_CAN4_IO_IF1MCTR4:	.res.b	2
_IO_CAN4_IO_RESV2:	.res.b	2
_IO_CAN4_IO_IF1DTA14:	.res.b	2
_IO_CAN4_IO_IF1DTA24:	.res.b	2
_IO_CAN4_IO_IF1DTB14:	.res.b	2
_IO_CAN4_IO_IF1DTB24:	.res.b	2
_IO_CAN4_IO_RESV3	.res.b	24
_IO_CAN4_IO_IF2CREQ4:	.res.b	2
_IO_CAN4_IO_IF2CMSK4:	.res.b	2
_IO_CAN4_IO_IF2MSK4:	.res.b	4
_IO_CAN4_IO_IF2ARB4:	.res.b	4
_IO_CAN4_IO_IF2MCTR4:	.res.b	2
_IO_CAN4_IO_RESV4:	.res.b	2
_IO_CAN4_IO_IF2DTA14:	.res.b	2
_IO_CAN4_IO_IF2DTA24:	.res.b	2
_IO_CAN4_IO_IF2DTB14:	.res.b	2
_IO_CAN4_IO_IF2DTB24:	.res.b	2
_IO_CAN4_IO_RESV5	.res.b	40
_IO_CAN4_IO_TREQR4_12:	.res.b	4
_IO_CAN4_IO_RESV6:	.res.b	4
_IO_CAN4_IO_RESV7:	.res.b	4
_IO_CAN4_IO_RESV8:	.res.b	4
_IO_CAN4_IO_NEWDT4_12:	.res.b	4
_IO_CAN4_IO_RESV9:	.res.b	4
_IO_CAN4_IO_RESV10:	.res.b	4
_IO_CAN4_IO_RESV11:	.res.b	4
_IO_CAN4_IO_INTPND4_12:	.res.b	4
_IO_CAN4_IO_RESV12:	.res.b	4
_IO_CAN4_IO_RESV13:	.res.b	4
_IO_CAN4_IO_RESV14:	.res.b	4
_IO_CAN4_IO_MSGVAL4_12:	.res.b	4
_IO_CAN4_IO_RESV15:	.res.b	4
_IO_CAN4_IO_RESV16:	.res.b	4
_IO_CAN4_IO_RESV17:	.res.b	4
#endif
	.GLOBAL	_IO_CAN4
	.GLOBAL	_IO_CAN4_IO_CTRLR4
	.GLOBAL	_IO_CAN4_IO_STATR4
	.GLOBAL	_IO_CAN4_IO_ERRCNT4
	.GLOBAL	_IO_CAN4_IO_BTR4
	.GLOBAL	_IO_CAN4_IO_INTR4
	.GLOBAL	_IO_CAN4_IO_TESTR4
	.GLOBAL	_IO_CAN4_IO_BRPER4
	.GLOBAL	_IO_CAN4_IO_RESV1
	.GLOBAL	_IO_CAN4_IO_IF1CREQ4
	.GLOBAL	_IO_CAN4_IO_IF1CMSK4
	.GLOBAL	_IO_CAN4_IO_IF1MSK4
	.GLOBAL	_IO_CAN4_IO_IF1ARB4
	.GLOBAL	_IO_CAN4_IO_IF1MCTR4
	.GLOBAL	_IO_CAN4_IO_RESV2
	.GLOBAL	_IO_CAN4_IO_IF1DTA14
	.GLOBAL	_IO_CAN4_IO_IF1DTA24
	.GLOBAL	_IO_CAN4_IO_IF1DTB14
	.GLOBAL	_IO_CAN4_IO_IF1DTB24
	.GLOBAL	_IO_CAN4_IO_RESV3
	.GLOBAL	_IO_CAN4_IO_RESV3_0
	.GLOBAL	_IO_CAN4_IO_RESV3_1
	.GLOBAL	_IO_CAN4_IO_RESV3_2
	.GLOBAL	_IO_CAN4_IO_RESV3_3
	.GLOBAL	_IO_CAN4_IO_RESV3_4
	.GLOBAL	_IO_CAN4_IO_RESV3_5
	.GLOBAL	_IO_CAN4_IO_RESV3_6
	.GLOBAL	_IO_CAN4_IO_RESV3_7
	.GLOBAL	_IO_CAN4_IO_RESV3_8
	.GLOBAL	_IO_CAN4_IO_RESV3_9
	.GLOBAL	_IO_CAN4_IO_RESV3_10
	.GLOBAL	_IO_CAN4_IO_RESV3_11
	.GLOBAL	_IO_CAN4_IO_RESV3_12
	.GLOBAL	_IO_CAN4_IO_RESV3_13
	.GLOBAL	_IO_CAN4_IO_RESV3_14
	.GLOBAL	_IO_CAN4_IO_RESV3_15
	.GLOBAL	_IO_CAN4_IO_RESV3_16
	.GLOBAL	_IO_CAN4_IO_RESV3_17
	.GLOBAL	_IO_CAN4_IO_RESV3_18
	.GLOBAL	_IO_CAN4_IO_RESV3_19
	.GLOBAL	_IO_CAN4_IO_RESV3_20
	.GLOBAL	_IO_CAN4_IO_RESV3_21
	.GLOBAL	_IO_CAN4_IO_RESV3_22
	.GLOBAL	_IO_CAN4_IO_RESV3_23
	.GLOBAL	_IO_CAN4_IO_IF2CREQ4
	.GLOBAL	_IO_CAN4_IO_IF2CMSK4
	.GLOBAL	_IO_CAN4_IO_IF2MSK4
	.GLOBAL	_IO_CAN4_IO_IF2ARB4
	.GLOBAL	_IO_CAN4_IO_IF2MCTR4
	.GLOBAL	_IO_CAN4_IO_RESV4
	.GLOBAL	_IO_CAN4_IO_IF2DTA14
	.GLOBAL	_IO_CAN4_IO_IF2DTA24
	.GLOBAL	_IO_CAN4_IO_IF2DTB14
	.GLOBAL	_IO_CAN4_IO_IF2DTB24
	.GLOBAL	_IO_CAN4_IO_RESV5
	.GLOBAL	_IO_CAN4_IO_RESV5_0
	.GLOBAL	_IO_CAN4_IO_RESV5_1
	.GLOBAL	_IO_CAN4_IO_RESV5_2
	.GLOBAL	_IO_CAN4_IO_RESV5_3
	.GLOBAL	_IO_CAN4_IO_RESV5_4
	.GLOBAL	_IO_CAN4_IO_RESV5_5
	.GLOBAL	_IO_CAN4_IO_RESV5_6
	.GLOBAL	_IO_CAN4_IO_RESV5_7
	.GLOBAL	_IO_CAN4_IO_RESV5_8
	.GLOBAL	_IO_CAN4_IO_RESV5_9
	.GLOBAL	_IO_CAN4_IO_RESV5_10
	.GLOBAL	_IO_CAN4_IO_RESV5_11
	.GLOBAL	_IO_CAN4_IO_RESV5_12
	.GLOBAL	_IO_CAN4_IO_RESV5_13
	.GLOBAL	_IO_CAN4_IO_RESV5_14
	.GLOBAL	_IO_CAN4_IO_RESV5_15
	.GLOBAL	_IO_CAN4_IO_RESV5_16
	.GLOBAL	_IO_CAN4_IO_RESV5_17
	.GLOBAL	_IO_CAN4_IO_RESV5_18
	.GLOBAL	_IO_CAN4_IO_RESV5_19
	.GLOBAL	_IO_CAN4_IO_RESV5_20
	.GLOBAL	_IO_CAN4_IO_RESV5_21
	.GLOBAL	_IO_CAN4_IO_RESV5_22
	.GLOBAL	_IO_CAN4_IO_RESV5_23
	.GLOBAL	_IO_CAN4_IO_RESV5_24
	.GLOBAL	_IO_CAN4_IO_RESV5_25
	.GLOBAL	_IO_CAN4_IO_RESV5_26
	.GLOBAL	_IO_CAN4_IO_RESV5_27
	.GLOBAL	_IO_CAN4_IO_RESV5_28
	.GLOBAL	_IO_CAN4_IO_RESV5_29
	.GLOBAL	_IO_CAN4_IO_RESV5_30
	.GLOBAL	_IO_CAN4_IO_RESV5_31
	.GLOBAL	_IO_CAN4_IO_RESV5_32
	.GLOBAL	_IO_CAN4_IO_RESV5_33
	.GLOBAL	_IO_CAN4_IO_RESV5_34
	.GLOBAL	_IO_CAN4_IO_RESV5_35
	.GLOBAL	_IO_CAN4_IO_RESV5_36
	.GLOBAL	_IO_CAN4_IO_RESV5_37
	.GLOBAL	_IO_CAN4_IO_RESV5_38
	.GLOBAL	_IO_CAN4_IO_RESV5_39
	.GLOBAL	_IO_CAN4_IO_TREQR4_12
	.GLOBAL	_IO_CAN4_IO_RESV6
	.GLOBAL	_IO_CAN4_IO_RESV7
	.GLOBAL	_IO_CAN4_IO_RESV8
	.GLOBAL	_IO_CAN4_IO_NEWDT4_12
	.GLOBAL	_IO_CAN4_IO_RESV9
	.GLOBAL	_IO_CAN4_IO_RESV10
	.GLOBAL	_IO_CAN4_IO_RESV11
	.GLOBAL	_IO_CAN4_IO_INTPND4_12
	.GLOBAL	_IO_CAN4_IO_RESV12
	.GLOBAL	_IO_CAN4_IO_RESV13
	.GLOBAL	_IO_CAN4_IO_RESV14
	.GLOBAL	_IO_CAN4_IO_MSGVAL4_12
	.GLOBAL	_IO_CAN4_IO_RESV15
	.GLOBAL	_IO_CAN4_IO_RESV16
	.GLOBAL	_IO_CAN4_IO_RESV17

#ifdef __IO_DEFINE
	.SECTION	IO_FxR_CIF,DATA,locate=0xD000
_IO_FxR_CIF:	.res.b	0
_IO_FxR_CIF_IO_CIF0:	.res.b	4
_IO_FxR_CIF_IO_CIF1:	.res.b	4
#endif
	.GLOBAL	_IO_FxR_CIF
	.GLOBAL	_IO_FxR_CIF_IO_CIF0
	.GLOBAL	_IO_FxR_CIF_IO_CIF1

#ifdef __IO_DEFINE
	.SECTION	IO_FxR_GIF1,DATA,locate=0xD010
_IO_FxR_GIF1:	.res.b	0
_IO_FxR_GIF1_IO_TEST1:	.res.b	4
_IO_FxR_GIF1_IO_TEST2:	.res.b	4
_IO_FxR_GIF1_IO_RESV1:	.res.b	4
_IO_FxR_GIF1_IO_LCK:	.res.b	4
#endif
	.GLOBAL	_IO_FxR_GIF1
	.GLOBAL	_IO_FxR_GIF1_IO_TEST1
	.GLOBAL	_IO_FxR_GIF1_IO_TEST2
	.GLOBAL	_IO_FxR_GIF1_IO_RESV1
	.GLOBAL	_IO_FxR_GIF1_IO_LCK

#ifdef __IO_DEFINE
	.SECTION	IO_FxR_INT,DATA,locate=0xD020
_IO_FxR_INT:	.res.b	0
_IO_FxR_INT_IO_EIR:	.res.b	4
_IO_FxR_INT_IO_SIR:	.res.b	4
_IO_FxR_INT_IO_EILS:	.res.b	4
_IO_FxR_INT_IO_SILS:	.res.b	4
_IO_FxR_INT_IO_EIES:	.res.b	4
_IO_FxR_INT_IO_EIER:	.res.b	4
_IO_FxR_INT_IO_SIES:	.res.b	4
_IO_FxR_INT_IO_SIER:	.res.b	4
_IO_FxR_INT_IO_ILE:	.res.b	4
_IO_FxR_INT_IO_T0C:	.res.b	4
_IO_FxR_INT_IO_T1C:	.res.b	4
_IO_FxR_INT_IO_STPW1:	.res.b	4
_IO_FxR_INT_IO_STPW2:	.res.b	4
#endif
	.GLOBAL	_IO_FxR_INT
	.GLOBAL	_IO_FxR_INT_IO_EIR
	.GLOBAL	_IO_FxR_INT_IO_SIR
	.GLOBAL	_IO_FxR_INT_IO_EILS
	.GLOBAL	_IO_FxR_INT_IO_SILS
	.GLOBAL	_IO_FxR_INT_IO_EIES
	.GLOBAL	_IO_FxR_INT_IO_EIER
	.GLOBAL	_IO_FxR_INT_IO_SIES
	.GLOBAL	_IO_FxR_INT_IO_SIER
	.GLOBAL	_IO_FxR_INT_IO_ILE
	.GLOBAL	_IO_FxR_INT_IO_T0C
	.GLOBAL	_IO_FxR_INT_IO_T1C
	.GLOBAL	_IO_FxR_INT_IO_STPW1
	.GLOBAL	_IO_FxR_INT_IO_STPW2

#ifdef __IO_DEFINE
	.SECTION	IO_FxR_SUC1,DATA,locate=0xD080
_IO_FxR_SUC1:	.res.b	0
_IO_FxR_SUC1_IO_SUCC1:	.res.b	4
_IO_FxR_SUC1_IO_SUCC2:	.res.b	4
_IO_FxR_SUC1_IO_SUCC3:	.res.b	4
#endif
	.GLOBAL	_IO_FxR_SUC1
	.GLOBAL	_IO_FxR_SUC1_IO_SUCC1
	.GLOBAL	_IO_FxR_SUC1_IO_SUCC2
	.GLOBAL	_IO_FxR_SUC1_IO_SUCC3

#ifdef __IO_DEFINE
	.SECTION	IO_FxR_NEMC,DATA,locate=0xD08C
_IO_FxR_NEMC:
__fxr_nemc:	.res.b	4
FxR_NEMC	.equ	0xD08C
#endif
	.GLOBAL	_IO_FxR_NEMC, __fxr_nemc, FxR_NEMC

#ifdef __IO_DEFINE
	.SECTION	IO_FxR_PRT,DATA,locate=0xD090
_IO_FxR_PRT:	.res.b	0
_IO_FxR_PRT_IO_PRTC1:	.res.b	4
_IO_FxR_PRT_IO_PRTC2:	.res.b	4
#endif
	.GLOBAL	_IO_FxR_PRT
	.GLOBAL	_IO_FxR_PRT_IO_PRTC1
	.GLOBAL	_IO_FxR_PRT_IO_PRTC2

#ifdef __IO_DEFINE
	.SECTION	IO_FxR_MHDC,DATA,locate=0xD098
_IO_FxR_MHDC:
__fxr_mhdc:	.res.b	4
FxR_MHDC	.equ	0xD098
#endif
	.GLOBAL	_IO_FxR_MHDC, __fxr_mhdc, FxR_MHDC

#ifdef __IO_DEFINE
	.SECTION	IO_FxR_GTU1,DATA,locate=0xD0A0
_IO_FxR_GTU1:	.res.b	0
_IO_FxR_GTU1_IO_GTUC1:	.res.b	4
_IO_FxR_GTU1_IO_GTUC2:	.res.b	4
_IO_FxR_GTU1_IO_GTUC3:	.res.b	4
_IO_FxR_GTU1_IO_GTUC4:	.res.b	4
_IO_FxR_GTU1_IO_GTUC5:	.res.b	4
_IO_FxR_GTU1_IO_GTUC6:	.res.b	4
_IO_FxR_GTU1_IO_GTUC7:	.res.b	4
_IO_FxR_GTU1_IO_GTUC8:	.res.b	4
_IO_FxR_GTU1_IO_GTUC9:	.res.b	4
_IO_FxR_GTU1_IO_GTUC10:	.res.b	4
_IO_FxR_GTU1_IO_GTUC11:	.res.b	4
#endif
	.GLOBAL	_IO_FxR_GTU1
	.GLOBAL	_IO_FxR_GTU1_IO_GTUC1
	.GLOBAL	_IO_FxR_GTU1_IO_GTUC2
	.GLOBAL	_IO_FxR_GTU1_IO_GTUC3
	.GLOBAL	_IO_FxR_GTU1_IO_GTUC4
	.GLOBAL	_IO_FxR_GTU1_IO_GTUC5
	.GLOBAL	_IO_FxR_GTU1_IO_GTUC6
	.GLOBAL	_IO_FxR_GTU1_IO_GTUC7
	.GLOBAL	_IO_FxR_GTU1_IO_GTUC8
	.GLOBAL	_IO_FxR_GTU1_IO_GTUC9
	.GLOBAL	_IO_FxR_GTU1_IO_GTUC10
	.GLOBAL	_IO_FxR_GTU1_IO_GTUC11

#ifdef __IO_DEFINE
	.SECTION	IO_FxR_SUC2,DATA,locate=0xD100
_IO_FxR_SUC2:	.res.b	0
_IO_FxR_SUC2_IO_CCSV:	.res.b	4
_IO_FxR_SUC2_IO_CCEV:	.res.b	4
#endif
	.GLOBAL	_IO_FxR_SUC2
	.GLOBAL	_IO_FxR_SUC2_IO_CCSV
	.GLOBAL	_IO_FxR_SUC2_IO_CCEV

#ifdef __IO_DEFINE
	.SECTION	IO_FxR_GTU2,DATA,locate=0xD110
_IO_FxR_GTU2:	.res.b	0
_IO_FxR_GTU2_IO_SCV:	.res.b	4
_IO_FxR_GTU2_IO_MTCCV:	.res.b	4
_IO_FxR_GTU2_IO_RCV:	.res.b	4
_IO_FxR_GTU2_IO_OCV:	.res.b	4
_IO_FxR_GTU2_IO_SFS:	.res.b	4
_IO_FxR_GTU2_IO_SWNIT:	.res.b	4
_IO_FxR_GTU2_IO_ACS:	.res.b	4
_IO_FxR_GTU2_IO_RESV1:	.res.b	4
_IO_FxR_GTU2_IO_ESID_0:	.res.b	0
_IO_FxR_GTU2_IO_ESID_1:	.res.b	0
_IO_FxR_GTU2_IO_ESID_2:	.res.b	0
_IO_FxR_GTU2_IO_ESID_3:	.res.b	0
_IO_FxR_GTU2_IO_ESID_4:	.res.b	0
_IO_FxR_GTU2_IO_ESID_5:	.res.b	0
_IO_FxR_GTU2_IO_ESID_6:	.res.b	0
_IO_FxR_GTU2_IO_ESID_7:	.res.b	0
_IO_FxR_GTU2_IO_ESID_8:	.res.b	0
_IO_FxR_GTU2_IO_ESID_9:	.res.b	0
_IO_FxR_GTU2_IO_ESID_10:	.res.b	0
_IO_FxR_GTU2_IO_ESID_11:	.res.b	0
_IO_FxR_GTU2_IO_ESID_12:	.res.b	0
_IO_FxR_GTU2_IO_ESID_13:	.res.b	0
_IO_FxR_GTU2_IO_ESID_14:	.res.b	60
_IO_FxR_GTU2_IO_RESV2:	.res.b	4
_IO_FxR_GTU2_IO_OSID_0:	.res.b	0
_IO_FxR_GTU2_IO_OSID_1:	.res.b	0
_IO_FxR_GTU2_IO_OSID_2:	.res.b	0
_IO_FxR_GTU2_IO_OSID_3:	.res.b	0
_IO_FxR_GTU2_IO_OSID_4:	.res.b	0
_IO_FxR_GTU2_IO_OSID_5:	.res.b	0
_IO_FxR_GTU2_IO_OSID_6:	.res.b	0
_IO_FxR_GTU2_IO_OSID_7:	.res.b	0
_IO_FxR_GTU2_IO_OSID_8:	.res.b	0
_IO_FxR_GTU2_IO_OSID_9:	.res.b	0
_IO_FxR_GTU2_IO_OSID_10:	.res.b	0
_IO_FxR_GTU2_IO_OSID_11:	.res.b	0
_IO_FxR_GTU2_IO_OSID_12:	.res.b	0
_IO_FxR_GTU2_IO_OSID_13:	.res.b	0
_IO_FxR_GTU2_IO_OSID_14:	.res.b	60
#endif
	.GLOBAL	_IO_FxR_GTU2
	.GLOBAL	_IO_FxR_GTU2_IO_SCV
	.GLOBAL	_IO_FxR_GTU2_IO_MTCCV
	.GLOBAL	_IO_FxR_GTU2_IO_RCV
	.GLOBAL	_IO_FxR_GTU2_IO_OCV
	.GLOBAL	_IO_FxR_GTU2_IO_SFS
	.GLOBAL	_IO_FxR_GTU2_IO_SWNIT
	.GLOBAL	_IO_FxR_GTU2_IO_ACS
	.GLOBAL	_IO_FxR_GTU2_IO_RESV1
	.GLOBAL	_IO_FxR_GTU2_IO_ESID_0
	.GLOBAL	_IO_FxR_GTU2_IO_ESID_1
	.GLOBAL	_IO_FxR_GTU2_IO_ESID_2
	.GLOBAL	_IO_FxR_GTU2_IO_ESID_3
	.GLOBAL	_IO_FxR_GTU2_IO_ESID_4
	.GLOBAL	_IO_FxR_GTU2_IO_ESID_5
	.GLOBAL	_IO_FxR_GTU2_IO_ESID_6
	.GLOBAL	_IO_FxR_GTU2_IO_ESID_7
	.GLOBAL	_IO_FxR_GTU2_IO_ESID_8
	.GLOBAL	_IO_FxR_GTU2_IO_ESID_9
	.GLOBAL	_IO_FxR_GTU2_IO_ESID_10
	.GLOBAL	_IO_FxR_GTU2_IO_ESID_11
	.GLOBAL	_IO_FxR_GTU2_IO_ESID_12
	.GLOBAL	_IO_FxR_GTU2_IO_ESID_13
	.GLOBAL	_IO_FxR_GTU2_IO_ESID_14
	.GLOBAL	_IO_FxR_GTU2_IO_RESV2
	.GLOBAL	_IO_FxR_GTU2_IO_OSID_0
	.GLOBAL	_IO_FxR_GTU2_IO_OSID_1
	.GLOBAL	_IO_FxR_GTU2_IO_OSID_2
	.GLOBAL	_IO_FxR_GTU2_IO_OSID_3
	.GLOBAL	_IO_FxR_GTU2_IO_OSID_4
	.GLOBAL	_IO_FxR_GTU2_IO_OSID_5
	.GLOBAL	_IO_FxR_GTU2_IO_OSID_6
	.GLOBAL	_IO_FxR_GTU2_IO_OSID_7
	.GLOBAL	_IO_FxR_GTU2_IO_OSID_8
	.GLOBAL	_IO_FxR_GTU2_IO_OSID_9
	.GLOBAL	_IO_FxR_GTU2_IO_OSID_10
	.GLOBAL	_IO_FxR_GTU2_IO_OSID_11
	.GLOBAL	_IO_FxR_GTU2_IO_OSID_12
	.GLOBAL	_IO_FxR_GTU2_IO_OSID_13
	.GLOBAL	_IO_FxR_GTU2_IO_OSID_14

#ifdef __IO_DEFINE
	.SECTION	IO_FxR_NMV,DATA,locate=0xD1B0
_IO_FxR_NMV:
__FxR_NMV:	.res.b	12
FxR_NMV	.equ	0xD1B0
#endif
	.GLOBAL	_IO_FxR_NMV, __FxR_NMV, FxR_NMV

#ifdef __IO_DEFINE
	.SECTION	IO_FxR_MHD,DATA,locate=0xD300
_IO_FxR_MHD:	.res.b	0
_IO_FxR_MHD_IO_MRC:	.res.b	4
_IO_FxR_MHD_IO_FRF:	.res.b	4
_IO_FxR_MHD_IO_FRFM:	.res.b	4
_IO_FxR_MHD_IO_FCL:	.res.b	4
_IO_FxR_MHD_IO_MHDS:	.res.b	4
_IO_FxR_MHD_IO_LDTS:	.res.b	4
_IO_FxR_MHD_IO_FSR:	.res.b	4
_IO_FxR_MHD_IO_MHDF:	.res.b	4
_IO_FxR_MHD_IO_TXRQ1:	.res.b	4
_IO_FxR_MHD_IO_TXRQ2:	.res.b	4
_IO_FxR_MHD_IO_TXRQ3:	.res.b	4
_IO_FxR_MHD_IO_TXRQ4:	.res.b	4
_IO_FxR_MHD_IO_NDAT1:	.res.b	4
_IO_FxR_MHD_IO_NDAT2:	.res.b	4
_IO_FxR_MHD_IO_NDAT3:	.res.b	4
_IO_FxR_MHD_IO_NDAT4:	.res.b	4
_IO_FxR_MHD_IO_MBSC1:	.res.b	4
_IO_FxR_MHD_IO_MBSC2:	.res.b	4
_IO_FxR_MHD_IO_MBSC3:	.res.b	4
_IO_FxR_MHD_IO_MBSC4:	.res.b	4
#endif
	.GLOBAL	_IO_FxR_MHD
	.GLOBAL	_IO_FxR_MHD_IO_MRC
	.GLOBAL	_IO_FxR_MHD_IO_FRF
	.GLOBAL	_IO_FxR_MHD_IO_FRFM
	.GLOBAL	_IO_FxR_MHD_IO_FCL
	.GLOBAL	_IO_FxR_MHD_IO_MHDS
	.GLOBAL	_IO_FxR_MHD_IO_LDTS
	.GLOBAL	_IO_FxR_MHD_IO_FSR
	.GLOBAL	_IO_FxR_MHD_IO_MHDF
	.GLOBAL	_IO_FxR_MHD_IO_TXRQ1
	.GLOBAL	_IO_FxR_MHD_IO_TXRQ2
	.GLOBAL	_IO_FxR_MHD_IO_TXRQ3
	.GLOBAL	_IO_FxR_MHD_IO_TXRQ4
	.GLOBAL	_IO_FxR_MHD_IO_NDAT1
	.GLOBAL	_IO_FxR_MHD_IO_NDAT2
	.GLOBAL	_IO_FxR_MHD_IO_NDAT3
	.GLOBAL	_IO_FxR_MHD_IO_NDAT4
	.GLOBAL	_IO_FxR_MHD_IO_MBSC1
	.GLOBAL	_IO_FxR_MHD_IO_MBSC2
	.GLOBAL	_IO_FxR_MHD_IO_MBSC3
	.GLOBAL	_IO_FxR_MHD_IO_MBSC4

#ifdef __IO_DEFINE
	.SECTION	IO_FxR_GIF2,DATA,locate=0xD3F0
_IO_FxR_GIF2:	.res.b	0
_IO_FxR_GIF2_IO_CREL:	.res.b	4
_IO_FxR_GIF2_IO_ENDN:	.res.b	4
#endif
	.GLOBAL	_IO_FxR_GIF2
	.GLOBAL	_IO_FxR_GIF2_IO_CREL
	.GLOBAL	_IO_FxR_GIF2_IO_ENDN

#ifdef __IO_DEFINE
	.SECTION	IO_FxR_WRDS,DATA,locate=0xD400
_IO_FxR_WRDS:
__FxR_WRDS:	.res.b	256
FxR_WRDS	.equ	0xD400
#endif
	.GLOBAL	_IO_FxR_WRDS, __FxR_WRDS, FxR_WRDS

#ifdef __IO_DEFINE
	.SECTION	IO_FxR_IBF,DATA,locate=0xD500
_IO_FxR_IBF:	.res.b	0
_IO_FxR_IBF_IO_WRHS1:	.res.b	4
_IO_FxR_IBF_IO_WRHS2:	.res.b	4
_IO_FxR_IBF_IO_WRHS3:	.res.b	4
_IO_FxR_IBF_IO_RESV1:	.res.b	4
_IO_FxR_IBF_IO_IBCM:	.res.b	4
_IO_FxR_IBF_IO_IBCR:	.res.b	4
#endif
	.GLOBAL	_IO_FxR_IBF
	.GLOBAL	_IO_FxR_IBF_IO_WRHS1
	.GLOBAL	_IO_FxR_IBF_IO_WRHS2
	.GLOBAL	_IO_FxR_IBF_IO_WRHS3
	.GLOBAL	_IO_FxR_IBF_IO_RESV1
	.GLOBAL	_IO_FxR_IBF_IO_IBCM
	.GLOBAL	_IO_FxR_IBF_IO_IBCR

#ifdef __IO_DEFINE
	.SECTION	IO_FxR_RDDS,DATA,locate=0xD600
_IO_FxR_RDDS:
__FxR_RDDS:	.res.b	256
FxR_RDDS	.equ	0xD600
#endif
	.GLOBAL	_IO_FxR_RDDS, __FxR_RDDS, FxR_RDDS

#ifdef __IO_DEFINE
	.SECTION	IO_FxR_OBF,DATA,locate=0xD700
_IO_FxR_OBF:	.res.b	0
_IO_FxR_OBF_IO_RDHS1:	.res.b	4
_IO_FxR_OBF_IO_RDHS2:	.res.b	4
_IO_FxR_OBF_IO_RDHS3:	.res.b	4
_IO_FxR_OBF_IO_MBS:	.res.b	4
_IO_FxR_OBF_IO_OBCM:	.res.b	4
_IO_FxR_OBF_IO_OBCR:	.res.b	4
#endif
	.GLOBAL	_IO_FxR_OBF
	.GLOBAL	_IO_FxR_OBF_IO_RDHS1
	.GLOBAL	_IO_FxR_OBF_IO_RDHS2
	.GLOBAL	_IO_FxR_OBF_IO_RDHS3
	.GLOBAL	_IO_FxR_OBF_IO_MBS
	.GLOBAL	_IO_FxR_OBF_IO_OBCM
	.GLOBAL	_IO_FxR_OBF_IO_OBCR
